<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="en-US">
<head>
<meta charset="utf-8"/>
<meta name="generator" content="packt"/>
<title>12 Scanning, Auditing, and Hardening</title>



</head>
<body>

<h1 data-number="13">12 Scanning, Auditing, and Hardening</h1>

<h2 data-number="13.1">Join our book community on Discord</h2>
<p><a href="https://packt.link/SecNet">https://packt.link/SecNet</a></p>
<figure>
<img src="img/file74.png" style="width:10em" />
</figure>
<p>A common misconception is that Linux users never need to worry about malware. Yes, it's true that Linux is much more resistant to viruses than Windows is. But viruses are only one type of malware, and other types of malware can be planted on Linux machines. And, if you're running a server that will share files with Windows users, you'll want to make sure that you don't share any virus-infected files with them.</p>
<p>While Linux system log files are nice, they don't always give a good picture of who does what or who accesses what. It could be that either intruders or insiders are trying to access data that they're not authorized to access. What we really want is a good auditing system to alert us when people do things that they're not supposed to do.</p>
<p>And then there's the issue of regulatory compliance. Your organization may have to deal with one or more regulatory bodies that dictate how you harden your servers against attacks. If you're not in compliance, you could be fined or put out of business.</p>
<p>Fortunately, we have ways to deal with all of these issues, and they aren't all that complicated.</p>
<p>In this chapter, we'll cover the following topics:</p>
<ul>
<li>Installing and updating ClamAV and maldet</li>
<li>Scanning with ClamAV and maldet</li>
<li>SELinux considerations</li>
<li>Scanning for rootkits with Rootkit Hunter</li>
<li>Performing quick malware analysis with strings and VirusTotal</li>
<li>Controlling the <code>auditd</code> daemon</li>
<li>Creating audit rules</li>
<li>Using the <code>ausearch</code> and <code>aureport</code> utilities to search the audit logs for problems</li>
<li>Using <code>inotifywait</code> for quick and easy auditing</li>
<li><code>oscap</code>, the command-line utility for managing and applying OpenSCAP policies</li>
<li>OpenSCAP Workbench, the GUI utility for managing and applying OpenSCAP policies</li>
<li>OpenSCAP policy files and the compliance standards that each of them is designed to meet</li>
<li>Applying a policy during operating system installation</li>
</ul>
<p>If you're ready, let's begin by looking at a Linux-based virus scanning solution.</p>


<h2 data-number="13.2">Installing and updating ClamAV and maldet</h2>
<div><pre><code>Although we don&#39;t have to worry much about viruses infecting our Linux machines, we do need to worry about sharing infected files with Windows users. ClamAV is a Free Open Source Software (FOSS) antivirus solution that is available for Linux, Windows, and macOS. The included freshclam utility allows you to update virus signatures.
Linux Malware Detect, which you&#39;ll often see abbreviated as either LMD or maldet, is another FOSS antivirus program that can work alongside ClamAV. (To save typing, I&#39;ll just refer to it as either LMD or maldet from now on.) As far as I know, it&#39;s not available in the repositories of any Linux distro, but it&#39;s still simple enough to install and configure. One of its features is that it automatically generates malware detection signatures when it sees malware on the network&#39;s edge intrusion detection systems. End users can also submit their own malware samples. When you install it, you&#39;ll get a systemd service that&#39;s already enabled and a cron job that will periodically update both the malware signatures and the program itself. It works with the Linux kernel&#39;s inotify capability to automatically monitor directories for files that have changed.</code></pre>
</div>
<blockquote>
<p>You can get all the nitty-gritty details about LMD at <a href="https://www.rfxn.com/projects/linux-malware-detect/">https://www.rfxn.com/projects/linux-malware-detect/</a>.</p>
</blockquote>
<p>The reason that we're installing ClamAV and LMD together is that, as the LMD folk freely admit, the ClamAV scan engine gives much better performance when scanning large file sets. Also, by having them both together, ClamAV can use the LMD malware signatures as well as its own malware signatures.</p>
<blockquote>
<p>Just to be clear...</p>
<blockquote>
<p>Viruses are a real problem for computers that run the Windows operating system. But, as far as anyone has been able to tell, there's no such thing as a virus that can harm a Linux-based operating system. So, the only real reason to run an antivirus solution on a Linux machine is to prevent infecting any Windows machines on your network. This means that you don't need to worry about installing an antivirus product on your Linux-based DNS servers, DHCP servers, and so forth. But, if you have a Linux-based email server, Samba server, download server, or any other Linux-based machine that shares files with Windows computers, then installing an antivirus solution is a good idea.</p>
</blockquote>
</blockquote>
<p>All right, so much for the theory. Let's get our hands dirty, shall we?</p>

<h3 data-number="13.2.1">Hands-on lab – installing ClamAV and maldet</h3>
<p>We'll begin by installing ClamAV. (It's in the normal repository for Ubuntu, but not for CentOS or AlmaLinux. For CentOS and AlmaLinux, you'll need to install the EPEL repository, as I showed you in <em>Chapter 1</em>, <em>Running Linux in a Virtual Environment</em>.) We'll also install <code>wget</code>, which we'll use to download LMD. For this lab, you can use Ubuntu, CentOS 7, or either version of AlmaLinux. Let's get started:</p>
<ul>
<li>The following command will install ClamAV, <code>inotify-tools</code> and <code>wget</code> on Ubuntu:</li>
</ul>
<div><pre><code>donnie@ubuntu3:~$ sudo apt install clamav wget inotify-tools</code></pre>
</div>
<p>The following command will install ClamAV, <code>inotify-tools</code>, and <code>wget</code> on CentOS 7:</p>
<div><pre><code>[donnie@localhost ~]$ sudo yum install clamav clamav-update wget inotify-tools</code></pre>
</div>
<p>For AlmaLinux 8 or AlmaLinux 9, do this:</p>
<div><pre><code>[donnie@localhost ~]$ sudo dnf install clamav clamav-update wget inotify-tools
[donnie@localhost ~]$ sudo systemctl enable --now clamav-freshclam</code></pre>
</div>
<p>Note that if you chose the <strong>Minimal</strong> installation option when creating a CentOS or an AlmaLinux virtual machine (VM), you may also have to install the <code>perl</code> and the <code>tar</code> packages.</p>
<p>For Ubuntu, the <code>clamav</code> package contains everything you need. For CentOS or AlmaLinux, you'll need to also install <code>clamav-update</code> in order to obtain virus updates.</p>
<p>The rest of the steps will be the same for either VM.</p>
<ol>
<li>Next, you'll download and install LMD.</li>
</ol>
<p>Here, you'll want to do something that I rarely tell people to do. That is, you'll want to log in to the root user shell. The reason is that, although the LMD installer works fine with <code>sudo</code>, you'll end up with the program files being owned by the user who performed the installation, instead of by the root user. Performing the installation from the root user's shell saves us the trouble of tracking down those files and changing the ownership. So, download the file as follows:</p>
<div><pre><code>sudo su -
wget http://www.rfxn.com/downloads/maldetect-current.tar.gz</code></pre>
</div>
<p>Now, you'll have the file in the root user's home directory.</p>
<ol>
<li>Extract the archive and enter the resultant directory:</li>
</ol>
<div><pre><code>tar xzvf maldetect-current.tar.gz
cd maldetect-1.6.4/</code></pre>
</div>
<ul>
<li>Run the installer. Once the installer finishes, copy the <code>README</code> file to your own home directory so that you can have it for ready reference. (This <code>README</code> file is the documentation for LMD.) Then, exit from the root user's shell back to your own shell:</li>
</ul>
<div><pre><code>root@ubuntu3:~/maldetect-1.6.4# ./install.sh
Created symlink from /etc/systemd/system/multi-user.target.wants/maldet.service to /usr/lib/systemd/system/maldet.service.
update-rc.d: error: initscript does not exist: /etc/init.d/maldet
. . .
. . .
maldet(22138): {sigup} signature set update completed
maldet(22138): {sigup} 15218 signatures (12485 MD5 | 1954 HEX | 779 YARA | 0 USER)
root@ubuntu3:~/maldetect-1.6.4# cp README /home/donnie
root@ubuntu3:~/maldetect-1.6.4# exit
logout
donnie@ubuntu3:~$</code></pre>
</div>
<p>As you see, the installer automatically creates the symbolic link that enables the <code>maldet</code> service, and it also automatically downloads and installs the newest malware signatures.</p>
<ol>
<li>For CentOS or AlmaLinux, the <code>maldet.service</code> file that the installer copied to the <code>/lib/systemd/system/</code> directory has the wrong SELinux context, which will prevent <code>maldet</code> from starting. Correct the SELinux context like this:</li>
</ol>
<div><pre><code>sudo restorecon /lib/systemd/system/maldet.service</code></pre>
</div>
<p>You've reached the end of the lab – congratulations!</p>


<h3 data-number="13.2.2">Hands-on lab – configuring maldet</h3>
<p>In previous versions, maldet was configured by default to automatically monitor and scan users' home directories. In its current version, the default is for it to only monitor the <code>/dev/shm/</code>, <code>/var/tmp/</code>, and <code>/tmp/</code> directories. We're going to reconfigure it so that we can add some directories. Let's get started:</p>
<ol>
<li>Open the <code>/usr/local/maldetect/conf.maldet</code> file for editing. Find these two lines:</li>
</ol>
<div><pre><code>default_monitor_mode=&quot;users&quot;
# default_monitor_mode=&quot;/usr/local/maldetect/monitor_paths&quot;</code></pre>
</div>
<p>Change them to look like this:</p>
<div><pre><code># default_monitor_mode=&quot;users&quot;
default_monitor_mode=&quot;/usr/local/maldetect/monitor_paths&quot;</code></pre>
</div>
<ol>
<li>At the top of the file, enable email alerts and set your username as the email address. The two lines should now look something like this:</li>
</ol>
<div><pre><code>email_alert=&quot;1&quot;
email_addr=&quot;donnie&quot;</code></pre>
</div>
<ol>
<li>LMD isn't already configured to move suspicious files to the <code>quarantine</code> folder, and we want to make it do that. Further down in the <code>conf.maldet</code> file, look for the line that says:</li>
</ol>
<div><pre><code>quarantine_hits=&quot;0&quot;</code></pre>
</div>
<ol>
<li>Change it to this:</li>
</ol>
<div><pre><code>quarantine_hits=&quot;1&quot;</code></pre>
</div>
<blockquote>
<p>You'll see a few other quarantine actions that you can configure, but, for now, this is all we need.</p>
</blockquote>
<ul>
<li>Save the <code>conf.maldet</code> file, because that's all the changes that we need to make to it.</li>
<li>Open the <code>/usr/local/maldetect/monitor_paths </code>file for editing. Add the directories that you want to monitor, like this:</li>
</ul>
<div><pre><code>/var/tmp
/tmp
/home
/root</code></pre>
</div>
<blockquote>
<p>Since viruses affect Windows and not Linux, just monitor the directories with files that will be shared with Windows machines.</p>
</blockquote>
<ul>
<li>After you save the file, start the <code>maldet</code> daemon:</li>
</ul>
<div><pre><code>sudo systemctl start maldet</code></pre>
</div>
<blockquote>
<p>You can add more directories to the <code>monitor_paths</code> file at any time, but remember to restart the <code>maldet</code> daemon any time that you do, in order to read in the new additions.</p>
</blockquote>
<p>You've reached the end of the lab – congratulations!</p>
<p>Now, let's talk about keeping ClamAV and maldet updated.</p>


<h3 data-number="13.2.3">Updating ClamAV and maldet</h3>
<p>The good news for busy admins is that you don't have to do anything to keep either of these updated. To verify that they are getting updated, we can look in the system log file:</p>
<div><pre><code>Dec 8 20:02:09 localhost freshclam[22326]: ClamAV update process started at Fri Dec 8 20:02:09 2017
Dec 8 20:02:29 localhost freshclam[22326]: Can&#39;t query current.cvd.clamav.net
Dec 8 20:02:29 localhost freshclam[22326]: Invalid DNS reply. Falling back to HTTP mode.
Dec 8 20:02:29 localhost freshclam[22326]: Reading CVD header (main.cvd):
Dec 8 20:02:35 localhost freshclam[22326]: OK
Dec 8 20:02:47 localhost freshclam[22326]: Downloading main-58.cdiff [100%]
Dec 8 20:03:19 localhost freshclam[22326]: main.cld updated (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
. . .
. . .
Dec 8 20:04:45 localhost freshclam[22326]: Downloading daily.cvd [100%]
. . .
. . .</code></pre>
</div>
<p>You'll see these same entries in either the Ubuntu logs, the CentOS logs, or the AlmaLinux logs. However, there is a difference between how the updates get run automatically.</p>
<p>Look in the <code>/lib/systemd/system/</code> directory of your Ubuntu or AlmaLinux VMs, and you’ll see the <code>clamav-freshclam.service</code> file:</p>
<div><pre><code>[donnie@localhost ~]$ cd /lib/systemd/system
[donnie@localhost system]$ ls -l clamav-freshclam.service 
-rw-r--r--. 1 root root 389 Nov  7 06:51 clamav-freshclam.service
[donnie@localhost system]$</code></pre>
</div>
<p>This service is automatically enabled and started on Ubuntu, but you’ll need to enable and start it yourself on AlmaLinux, like so:</p>
<div><pre><code>[donnie@localhost ~]$ sudo systemctl enable --now clamav-freshclam
Created symlink /etc/systemd/system/multi-user.target.wants/clamav-freshclam.service → /usr/lib/systemd/system/clamav-freshclam.service.
[donnie@localhost ~]$</code></pre>
</div>
<p>Without a <code>freshclam.conf</code> configuration file, AlmaLinux just runs the update service every two hours. Ubuntu, on the other hand, uses the <code>/etc/clamav/freshclam.conf</code> file to change the update interval to every hour, as you see at the bottom of the file:</p>
<div><pre><code># Check for new database 24 times a day
Checks 24
DatabaseMirror db.local.clamav.net
DatabaseMirror database.clamav.net</code></pre>
</div>
<blockquote>
<p>If you have the crypto policy set to <code>FUTURE</code> mode on your AlmaLinux 8/9 machine, the ClamAV database update won’t work. That’s because the ClamAV site uses a security certificate that’s not compatible with <code>FUTURE</code> mode. So, if you want to run ClamAV on any type of RHEL 8 or 9 machine, you’ll just have to leave the crypto policy set to <code>DEFAULT</code> mode.</p>
</blockquote>
<p>On your CentOS 7 machine, you'll see a <code>clamav-update</code> <code>cron</code> job in the <code>/etc/cron.d/</code> directory that looks like this:</p>
<div><pre><code>## Adjust this line...
MAILTO=root
## It is ok to execute it as root; freshclam drops privileges and becomes
## user &#39;clamupdate&#39; as soon as possible
0  */3 * * * root /usr/share/clamav/freshclam-sleep</code></pre>
</div>
<p>The <code>*/3</code> in the second column from the left indicates that ClamAV will check for updates every three hours. You can change that if you like, but you'll also need to change the setting in the <code>/etc/sysconfig/freshclam</code> file.</p>
<p>Let's say that you want CentOS 7 to also check for ClamAV updates every hour. In the <code>cron</code> job file, change <code>*/3</code> to <code>*</code>. (You don't need to do <code>*/1</code> because the asterisk by itself in that position already indicates that the job will run every hour.) Then, in the <code>/etc/sysconfig/freshclam</code> file, look for this line:</p>
<div><pre><code># FRESHCLAM_MOD=</code></pre>
</div>
<p>Uncomment that line and add the number of minutes that you want between updates. To set it to 1 hour, so that it matches the <code>cron</code> job, it will look like this:</p>
<div><pre><code>FRESHCLAM_MOD=60</code></pre>
</div>
<blockquote>
<p>A disabled <code>clamav-freshclam.service</code> file also gets installed on CentOS 7. If you’d rather use the service instead of the <code>cron</code> job, just delete the <code>/etc/cron.d/clamav-update</code> file, and then enable the <code>clamav-freshclam</code> service.</p>
</blockquote>
<p>To prove that <code>maldet</code> is being updated, you can look in its own log files in the <code>/usr/local/maldetect/logs/</code> directory. In the <code>event_log</code> file, you'll see these messages:</p>
<div><pre><code>Dec 06 22:06:14 localhost maldet(3728): {sigup} performing signature update check...
Dec 06 22:06:14 localhost maldet(3728): {sigup} local signature set is version 2017070716978
Dec 06 22:07:13 localhost maldet(3728): {sigup} downloaded https://cdn.rfxn.com/downloads/maldet.sigs.ver
Dec 06 22:07:13 localhost maldet(3728): {sigup} new signature set (201708255569) available
Dec 06 22:07:13 localhost maldet(3728): {sigup} downloading https://cdn.rfxn.com/downloads/maldet-sigpack.tgz
. . .
. . .
Dec 06 22:07:43 localhost maldet(3728): {sigup} unpacked and installed maldet-clean.tgz
Dec 06 22:07:43 localhost maldet(3728): {sigup} signature set update completed
Dec 06 22:07:43 localhost maldet(3728): {sigup} 15218 signatures (12485 MD5 | 1954 HEX | 779 YARA | 0 USER)
Dec 06 22:14:55 localhost maldet(4070): {scan} signatures loaded: 15218 (12485 MD5 | 1954 HEX | 779 YARA | 0 USER)</code></pre>
</div>
<p>In the <code>/usr/local/maldetect/conf.maldet</code> file, you'll see these two lines, but with some comments in between them:</p>
<div><pre><code>autoupdate_signatures=&quot;1&quot;
autoupdate_version=&quot;1&quot;</code></pre>
</div>
<p>Not only will LMD automatically update its malware signatures, but it will also ensure that you have the latest version of LMD itself.</p>



<h2 data-number="13.3">Scanning with ClamAV and maldet</h2>
<p>LMD's maldet daemon constantly monitors the directories that you specify in the <code>/usr/local/maldetect/monitor_paths</code> file. When it finds a suspicious file, it will perform the action that you specified in the <code>conf.maldet</code> file.</p>
<div><pre><code>You can test your setup by downloading a simulated virus file from the European Institute for Computer Antivirus Research (EICAR) site.</code></pre>
</div>
<blockquote>
<p>There are four different simulated virus files that you can download from <a href="https://www.eicar.org/download-anti-malware-testfile/">https://www.eicar.org/download-anti-malware-testfile/</a>. Note that if you’re running a Windows host machine, these files could get flagged by the Windows antivirus. So, your best bet is to download the files directly to your Linux virtual machines.</p>
</blockquote>
<p>Just download one or all of the EICAR test files and transfer them to your home directory on the virtual machines. Your best bet is to download the files directly to your virtual machines, with these four commands:</p>
<div><pre><code>wget https://secure.eicar.org/eicar.com
wget https://secure.eicar.org/eicar.com.txt
wget https://secure.eicar.org/eicar_com.zip
wget https://secure.eicar.org/eicarcom2.zip</code></pre>
</div>
<p>Wait just a few moments, and you should see the files disappear. Then, look in the <code>/usr/local/maldetect/logs/event_log</code> file to verify that the LMD moved the files to quarantine:</p>
<div><pre><code>Dec 01 15:18:31 localhost maldet(6388): {hit} malware hit {HEX}EICAR.TEST.3 found for /home/donnie/eicar.com.txt
Dec 01 15:18:31 localhost maldet(6388): {quar} malware quarantined from &#39;/home/donnie/eicar.com.txt&#39; to &#39;/usr/local/maldetect/quarantine/eicar.com.txt.113345162&#39;
Dec 01 15:18:31 localhost maldet(6388): {mon} scanned 5 new/changed files with clamav engine
Dec 01 15:20:32 localhost maldet(6388): {mon} warning clamd service not running; force-set monitor mode file scanning to every 120s
. . .
. . .
Dec 01 15:20:56 localhost maldet(6388): {quar} malware quarantined from &#39;/home/donnie/eicar_com.zip&#39; to &#39;/usr/local/maldetect/quarantine/eicar_com.zip.216978719&#39;</code></pre>
</div>
<blockquote>
<p>Ignore the <code>warning clamd service not running</code> messages, because we don’t need to use that service.</p>
</blockquote>
<p>There's still a bit more to LMD than what I can show you here. However, you can read all about it in the <code>README</code> file that comes with it.</p>

<h3 data-number="13.3.1">SELinux considerations</h3>
<p>It used to be that doing an antivirus scan on a Red Hat-type system would trigger an SELinux alert. But, in the course of proofing this chapter, the scans all worked as they should, and SELinux never bothered me once.</p>
<p>If you ever do generate any SELinux alerts with your virus scans, all you need to do to fix it is to change one Boolean:</p>
<div><pre><code>[donnie@localhost ~]$ getsebool -a | grep &#39;virus&#39;
antivirus_can_scan_system --&gt; off
antivirus_use_jit --&gt; off
[donnie@localhost ~]$</code></pre>
</div>
<p>What interests us here is the <code>antivirus_can_scan_system</code> Boolean, which is off by default. To turn it on to enable virus scans, just do this:</p>
<div><pre><code>[donnie@localhost ~]$ sudo setsebool -P antivirus_can_scan_system on
[sudo] password for donnie:
[donnie@localhost ~]$ getsebool antivirus_can_scan_system
antivirus_can_scan_system --&gt; on
[donnie@localhost ~]$</code></pre>
</div>
<p>That should fix any SELinux-related scan problems that you may have. But, as things stand now, you probably won't need to worry about it.</p>



<h2 data-number="13.4">Scanning for rootkits with Rootkit Hunter</h2>
<p>Rootkits are exceedingly nasty pieces of malware that can definitely ruin your day. They can listen for commands from their masters, steal sensitive data and send it to their masters, or provide an easy-access back door for their masters. They're designed to be stealthy, with the ability to hide themselves from plain view. Sometimes, they'll replace utilities such as <code>ls</code> or <code>ps</code> with their own trojaned versions that will show all files or processes on the system except for the ones that are associated with the rootkit. Rootkits can infect any operating system, even our beloved Linux.</p>
<p>In order to plant a rootkit, an attacker has to have already gained administrative privileges on a system. This is one of the many reasons why I always cringe when I see people doing all of their work from the root user's shell and why I'm a firm advocate of using <code>sudo</code> whenever possible. I mean, really, why should we make it easy for the bad guys?</p>
<blockquote>
<p>Several years ago, back in the dark days of Windows XP, Sony Music got into a bit of trouble when someone discovered that they had planted a rootkit on their music CDs. They didn't mean to do anything malicious, but only wanted to stop people from using their computers to make illegal copies. Of course, most people ran Windows XP with an administrator account, which made it really easy for the rootkit to infect their computers. Windows users still mostly run with administrator accounts, but they at least now have User Access Control to help mitigate these types of problems.</p>
</blockquote>
<p>There are a couple of different programs that scan for rootkits, and both are used pretty much the same way. One is called <strong>Rootkit Hunter</strong>, and the other is called <strong>chkrootkit</strong>. Now, understand that I’m showing you these programs because as a Linux administrator, you’ll be expected to know about them. In reality, they’re not very useful, because there are a whole lot of rootkits that neither of them will detect. If you really want to prove that, just go to Github and do a keyword search for <em>rootkit</em>. Find a rootkit that will run on Linux, download the source code to a virtual machine, and then follow the included directions for how to compile and install it. Once it’s installed, do a scan with either one of the rootkit scan programs. Most likely, the rootkit won’t get detected. Also, don’t expect AppArmor or SELinux to prevent someone from installing a rootkit, because they won’t.</p>
<blockquote>
<p>Not every rootkit on Github will compile correctly for you, so finding ones that work will involve a bit of trial-and-error. One that I did get to compile and install correctly is the Reptile rootkit, which you can download from here: <a href="https://github.com/f0rb1dd3n/Reptile">https://github.com/f0rb1dd3n/Reptile</a></p>
</blockquote>
<p>Okay, let's move on to the lab.</p>

<h3 data-number="13.4.1">Hands-on lab – installing and updating Rootkit Hunter</h3>
<p>For Ubuntu, Rootkit Hunter is in the normal repository. For CentOS or AlmaLinux, you'll need to install the EPEL repository, as I showed you how to do in <em>Chapter 1</em>, <em>Running Linux in a Virtual Environment</em>. For all of these Linux distros, the package name is <code>rkhunter</code>. Let's get started:</p>
<ol>
<li>Use one of the following commands to install Rootkit Hunter, as appropriate. For Ubuntu, do this:</li>
</ol>
<div><pre><code>sudo apt install rkhunter</code></pre>
</div>
<p>For CentOS 7, do the following:</p>
<div><pre><code>sudo yum install rkhunter</code></pre>
</div>
<p>For AlmaLinux 8 or AlmaLinux 9, do this:</p>
<div><pre><code>sudo dnf install rkhunter</code></pre>
</div>
<ol>
<li>After it's been installed, you can look at its options with this command:</li>
</ol>
<div><pre><code>man rkhunter</code></pre>
</div>
<ul>
<li>Next, update the rootkit signatures using the <code>--update</code> option:</li>
</ul>
<div><pre><code>[donnie@localhost ~]$ sudo rkhunter --update
[ Rootkit Hunter version 1.4.4 ]
Checking rkhunter data files...
 Checking file mirrors.dat [ Updated ]
 Checking file programs_bad.dat [ Updated ]
 Checking file backdoorports.dat [ No update ]
 Checking file suspscan.dat [ Updated ]
 Checking file i18n/cn [ No update ]
 Checking file i18n/de [ Updated ]
 Checking file i18n/en [ Updated ]
 Checking file i18n/tr [ Updated ]
 Checking file i18n/tr.utf8 [ Updated ]
 Checking file i18n/zh [ Updated ]
 Checking file i18n/zh.utf8 [ Updated ]
 Checking file i18n/ja [ Updated ]</code></pre>
</div>
<ol>
<li>Now, we're ready to scan.</li>
</ol>
<p>You've reached the end of the lab – congratulations!</p>


<h3 data-number="13.4.2">Scanning for rootkits</h3>
<p>To run your scan, use the <code>-c</code> option. (That's <code>-c</code> for <em>check</em>.) Be patient, because it will take a while:</p>
<div><pre><code>sudo rkhunter -c</code></pre>
</div>
<p>When you run the scan in this manner, Rootkit Hunter will periodically stop and ask you to hit the Enter key to continue. When the scan completes, you'll find a <code>rkhunter.log</code> file in the <code>/var/log/</code> directory.</p>
<p>To have Rootkit Hunter automatically run as a <code>cron</code> job, use the <code>--cronjob</code> option, which will cause the program to run all the way through without prompting you to keep hitting the Enter key. You might also want to use the <code>--rwo</code> option, which will cause the program to only report warnings, instead of also reporting on everything that's good. From the command line, the command would look like this:</p>
<div><pre><code>sudo rkhunter -c --cronjob --rwo</code></pre>
</div>
<p>To create a <code>cron</code> job that will automatically run Rootkit Hunter on a nightly basis, open the <code>crontab</code> editor for the root user:</p>
<div><pre><code>sudo crontab -e -u root</code></pre>
</div>
<p>Let's say that you want to run Rootkit Hunter every night at 20 minutes past 10. Enter this into the <code>crontab</code> editor:</p>
<div><pre><code>20 22 * * * /usr/bin/rkhunter -c --cronjob --rwo</code></pre>
</div>
<p>Since <code>cron</code> only works with 24-hour clock time, you'll have to express 10:00 P.M. as 22. (Just add 12 to the normal P.M. clock times that you're used to using.) The three asterisks mean that the job will run every day of the month, every month of the year, and every day of the week, respectively. You'll need to list the entire path for the command. Otherwise, <code>cron</code> won't be able to find it.</p>
<p>You'll find more options that might interest you in the <code>rkhunter</code> man page, but this should be enough to get you going with it.</p>
<blockquote>
<p>A few moments ago, I told you that these rootkit scanner programs aren’t very effective, because there are many rootkits that they won’t detect. That’s why the best way to deal with rootkits is to prevent them from getting installed in the first place. So, be sure to keep your systems locked down to prevent malicious actors from gaining root privileges.</p>
</blockquote>
<p>Next, let's look at a couple of quick techniques for analyzing malware.</p>



<h2 data-number="13.5">Performing a quick malware analysis with strings and VirusTotal</h2>
<p>Malware analysis is one of those advanced topics that I can't cover in detail here. However, I can show you a couple of quick ways to analyze a suspicious file.</p>

<h3 data-number="13.5.1">Analyze a file with strings</h3>
<p>Executable files often have strings of text embedded in them. You can use the <code>strings</code> utility to look at those strings. (Yeah, that makes sense, right?) Depending on your distro, <code>strings</code> might or might not already be installed. It's already on CentOS and AlmaLinux, but to get it on Ubuntu, you'll need to install the <code>binutils</code> package, like so:</p>
<div><pre><code>sudo apt install binutils</code></pre>
</div>
<p>As an example, let's look at a <code>Your File Is Ready To Download_2285169994.exe</code> file that was automatically downloaded from a cryptocoin faucet site. To examine the file, I’ll do this:</p>
<div><pre><code>strings &quot;Your File Is Ready To Download_2285169994.exe&quot; &gt; output.txt
vim output.txt</code></pre>
</div>
<p>I saved the output to a text file that I can open in <code>vim</code> so that I can view the line numbers. To see the line numbers, I entered <code>:set number</code> at the bottom of the <code>vim</code> screen. (In <code>vim</code> parlance, we're using the last line mode.)</p>
<p>It's hard to say exactly what to search for, so you'll just need to browse through until you see something interesting. In this case, look at what I've found starting at line <code>386</code>:</p>
<div><pre><code>386 The Setup program accepts optional command line parameters.
387 /HELP, /?
388 Shows this information.
389 /SP-
390 Disables the This will install... Do you wish to continue? prompt at the beginning of Setup.
391 /SILENT, /VERYSILENT
392 Instructs Setup to be silent or very silent.
393 /SUPPRESSMSGBOXES
394 Instructs Setup to suppress message boxes.
. . .
399 /NOCANCEL
400 Prevents the user from cancelling during the installation process.
. . .</code></pre>
</div>
<p>It's saying that the installation process of this program can be made to run in <code>SILENT</code> mode, without popping up any dialog boxes. It can also be made to run in such a way that the user can't cancel the installation. Of course, the line at the top says that these are <code>optional command line parameters</code>. But, are they really optional, or are they hard coded in as the default? It's not clear, but in my mind, any installer that can be made to run in <code>SILENT</code> mode and that can't be canceled looks a bit suspicious, even if we're talking about <code>optional</code> parameters.</p>
<blockquote>
<p>Okay, so you're probably wondering, <em>What is a cryptocoin faucet?</em> Well, it's a website where you can go to claim a small amount of cryptocoin, such as Bitcoin, Ethereum, or Monero, in exchange for viewing the advertising and solving some sort of CAPTCHA puzzle. Most faucet operators are honest, but the advertising they allow on their sites often isn't and is often laden with malware, scams, and Not-Safe-For-Work images.</p>
</blockquote>
<p>Now, this little trick works fine sometimes, but not always. More sophisticated malware might not contain any text strings that can give you any type of a clue. So, let's look at another little quick trick for malware analysis.</p>


<h3 data-number="13.5.2">Scanning the malware with VirusTotal</h3>
<p><strong>VirusTotal</strong> is a website where you can upload suspicious files for analysis. It uses a multitude of various virus scanners, so if one scanner misses something, another is likely to find it. Here are the results of scanning the <code>Your File Is Ready To Download_2285169994.exe</code> file:</p>
<figure>
<img src="img/file75.png" alt="Figure 12.1: The VirusTotal scanner" /><figcaption aria-hidden="true">Figure 12.1: The VirusTotal scanner</figcaption>
</figure>
<p>Here, we see that different virus scanners classify this file in different ways. But whether it's classified as <code>Win.Malware.Installcore</code>, <code>Trojan.InstallCore</code>, or whatever else, it's still bad.</p>
<blockquote>
<p>As good as VirusTotal is, you'll want to use it with caution. Don't upload any files that contain sensitive or confidential information, because it will get shared with other people.</p>
</blockquote>
<p>So, what is this particular piece of malware all about? Well, it's actually a fake Adobe Flash installer. Of course, you don't want to test that by installing it on a production Windows machine. But, if you have a Windows VM handy, you can test the malware on it. (Either make a snapshot of the VM before you begin or be prepared to trash the VM afterward.)</p>
<p>As I said at the beginning, malware analysis is quite an in-depth topic and there are lots of more sophisticated programs to use for it. However, if you have suspicions about something and need to just do a quick check, these two techniques might be all you need.</p>
<p>Next, let's look at how to automatically audit the system for different events.</p>



<h2 data-number="13.6">Understanding the auditd daemon</h2>
<p>So, you have a directory full of super-secret files that only a very few people need to see, and you want to know when unauthorized people try to see them. Or, maybe you want to see when a certain file gets changed, or you want to see when people log into the system and what they're doing once they do log in. For all this and more, you have the <code>auditd</code> system. It's a really cool system, and I think that you'll like it.</p>
<blockquote>
<p>One of the beauties of <code>auditd</code> is that it works at the Linux kernel level, rather than at the user-mode level. This makes it much harder for attackers to subvert.</p>
</blockquote>
<p>On Red Hat-type systems, <code>auditd</code> comes installed and enabled by default. So, you'll find it already there on your CentOS and AlmaLinux machines. On Ubuntu, it won't be installed, so you'll have to do it yourself:</p>
<div><pre><code>sudo apt install auditd</code></pre>
</div>
<p>On Ubuntu, you can control the <code>auditd</code> daemon with the normal <code>systemctl</code> commands. So, if you need to restart <code>auditd</code> to read in a new configuration, you can do that with:</p>
<div><pre><code>sudo systemctl restart auditd</code></pre>
</div>
<p>On RHEL-type machines, <code>auditd</code> is configured to not work with the normal <code>systemctl</code> commands. (For all other daemons, they do.) So, on your CentOS and AlmaLinux machines, you'll restart the <code>auditd</code> daemon with the old-fashioned <code>service</code> command, like so:</p>
<div><pre><code>sudo service auditd restart</code></pre>
</div>
<p>Other than this minor difference, everything I tell you about <code>auditd</code> from here on will apply to all of your virtual machines.</p>

<h3 data-number="13.6.1">Creating audit rules</h3>
<p>Okay, let's start with something simple and work our way up to something awesome. First, let's check to see whether any audit rules are in effect:</p>
<div><pre><code>[donnie@localhost ~]$ sudo auditctl -l
[sudo] password for donnie:
No rules
[donnie@localhost ~]$</code></pre>
</div>
<p>As you see, the <code>auditctl</code> command is what we use to manage audit rules. The <code>-l</code> option lists the rules.</p>


<h3 data-number="13.6.2">Auditing a file for changes</h3>
<p>Now, let's say that we want to see when someone changes the <code>/etc/passwd</code> file. (The command that we'll use will look a bit daunting, but I promise that it will make sense once we break it down.) Here goes:</p>
<div><pre><code>[donnie@localhost ~]$ sudo auditctl -w /etc/passwd -p wa -k passwd_changes
[sudo] password for donnie:
[donnie@localhost ~]$ sudo auditctl -l
-w /etc/passwd -p wa -k passwd_changes
[donnie@localhost ~]$</code></pre>
</div>
<p>Here's the breakdown:</p>
<ul>
<li><code>-w</code>: This stands for where, and it points to the object that we want to monitor. In this case, it's <code>/etc/passwd</code>.</li>
<li><code>-p</code>: This indicates the object's permissions that we want to monitor. In this case, we're monitoring to see when anyone either tries to (w)rite to the file or tries to make (a)ttribute changes. (The other two permissions that we can audit are (r)ead and e(x)ecute.)</li>
<li><code>-k</code>: The <code>k</code> stands for key, which is just <code>auditd</code>'s way of assigning a name to a rule. So, <code>passwd_changes</code> is the key, or the name, of the rule that we're creating.</li>
</ul>
<p>The <code>auditctl -l</code> command shows us that the rule is indeed there.</p>
<p>Now, the slight problem with this is that the rule is only temporary and will disappear when we reboot the machine. To make it permanent, we need to create a custom <code>rules</code> file in the <code>/etc/audit/rules.d/</code> directory. Then, when you restart the <code>auditd</code> daemon, the custom rules will be inserted into the <code>/etc/audit/audit.rules</code> file. Because the <code>/etc/audit/</code> directory can only be accessed by someone with root privileges, I'll just open the file by listing the entire path to the file, rather than trying to enter the directory:</p>
<div><pre><code>sudo less /etc/audit/audit.rules</code></pre>
</div>
<p>There's not a whole lot in this default file:</p>
<div><pre><code>## This file is automatically generated from /etc/audit/rules.d
-D
-b 8192
-f 1</code></pre>
</div>
<p>Here's the breakdown for this file:</p>
<ul>
<li><code>-D</code>: This will cause all rules and watches that are currently in effect to be deleted so that we can start from a clean slate. So, if I were to restart the <code>auditd</code> daemon right now, it would read this <code>audit.rules</code> file, which would delete the rule that I just created.</li>
<li><code>-b 8192</code>: This sets the number of outstanding audit buffers that we can have going at one time. If all of the buffers get full, the system can't generate any more audit messages.</li>
<li><code>-f 1</code>: This sets the failure mode for critical errors, and the value can be either <code>0</code>, <code>1</code>, or <code>2</code>. <code>-f 0</code> would set the mode to silent, meaning that <code>auditd</code> wouldn't do anything about critical errors. <code>-f 1</code>, as we see here, tells <code>auditd</code> to only report the critical errors, while <code>-f 2</code> would cause the Linux kernel to go into panic mode. According to the <code>auditctl</code> man page, anyone in a high-security environment would likely want to change this to <code>-f 2</code>. For our purposes, though, <code>-f1</code> works.</li>
</ul>
<p>You could use your text editor to create a new <code>rules</code> file in the <code>/etc/audit/rules.d/</code> directory. Alternatively, you could just redirect the <code>auditctl -l</code> output into a new file, like this:</p>
<div><pre><code>[donnie@localhost ~]$ sudo sh -c &quot;auditctl -l &gt; /etc/audit/rules.d/custom.rules&quot;
[donnie@localhost ~]$ sudo service auditd restart</code></pre>
</div>
<p>On Ubuntu:</p>
<p>sudo systemctl restart auditd</p>
<p>Since the Bash shell doesn't allow me to directly redirect information into a file in the <code>/etc/ </code>directory, even with <code>sudo</code>, I have to use the <code>sudo sh -c</code> command in order to execute the <code>auditctl</code> command. After restarting the <code>auditd</code> daemon, our <code>audit.rules</code> file now looks like this:</p>
<div><pre><code>## This file is automatically generated from /etc/audit/rules.d
-D
-b 8192
-f 1
-w /etc/passwd -p wa -k passwd_changes</code></pre>
</div>
<p>Now, the rule will take effect every time the machine is rebooted, and every time that you manually restart the <code>auditd</code> daemon.</p>


<h3 data-number="13.6.3">Auditing a directory</h3>
<p>Vicky and Cleopatra, my solid gray kitty and my gray-and-white tabby kitty, have some super sensitive secrets that they need to safeguard. So, I created the <code>secretcats</code> group and added them to it. Then, I created the <code>secretcats</code> shared directory and set the access controls on it, as I showed you how to do in <em>Chapter 9, Access Control Lists and Shared Directory Management</em>:</p>
<div><pre><code>[donnie@localhost ~]$ sudo groupadd secretcats
[sudo] password for donnie:
[donnie@localhost ~]$ sudo usermod -a -G secretcats vicky
[donnie@localhost ~]$ sudo usermod -a -G secretcats cleopatra
[donnie@localhost ~]$ sudo mkdir /secretcats
[donnie@localhost ~]$ sudo chown nobody:secretcats /secretcats/
[donnie@localhost ~]$ sudo chmod 3770 /secretcats/
[donnie@localhost ~]$ ls -ld /secretcats/
drwxrws--T. 2 nobody secretcats 6 Dec 11 14:47 /secretcats/
[donnie@localhost ~]$</code></pre>
</div>
<p>Vicky and Cleopatra want to be absolutely sure that nobody gets into their stuff, so they requested that I set up an auditing rule for their directory:</p>
<div><pre><code>[donnie@localhost ~]$ sudo auditctl -w /secretcats/ -k secretcats_watch
[sudo] password for donnie:
[donnie@localhost ~]$ sudo auditctl -l
-w /etc/passwd -p wa -k passwd_changes
-w /secretcats -p rwxa -k secretcats_watch
[donnie@localhost ~]$</code></pre>
</div>
<p>As before, the <code>-w</code> option denotes what we want to monitor, while the <code>-k</code> option denotes the name of the audit rule. This time, I left out the <code>-p</code> option because I want to monitor for every type of access. In other words, I want to monitor for any read, write, attribute change, or execute actions. (Because this is a directory, the execute action happens when somebody tries to <code>cd</code> into the directory.) You can see in the <code>auditctl -l</code> output that by leaving out the <code>-p</code> option, we will now monitor for everything. However, let's say that I only want to monitor for when someone tries to <code>cd</code> into this directory. I could have made the rule look like this:</p>
<div><pre><code>sudo auditctl -w /secretcats/ -p x -k secretcats_watch</code></pre>
</div>
<p>Easy enough so far, right?</p>
<blockquote>
<p>Plan carefully when you create your own custom audit rules. Auditing more files and directories than you need to can have a bit of a performance impact and could drown you in excessive information. Just audit what you really need to audit, as called for by either the scenario or what any applicable governing bodies require.</p>
</blockquote>
<p>Now, let's look at something a bit more complex.</p>


<h3 data-number="13.6.4">Auditing system calls</h3>
<p>Creating rules to monitor when someone performs a certain action isn't hard, but the command syntax is a bit trickier than what we've seen so far. With this rule, we're going to be alerted every time Charlie either tries to open a file or tries to create a file:</p>
<div><pre><code>[donnie@localhost ~]$ sudo auditctl -a always,exit -F arch=b64 -S openat -F auid=1006
[sudo] password for donnie:
[donnie@localhost ~]$ sudo auditctl -l
-w /etc/passwd -p wa -k passwd_changes
-w /secretcats -p rwxa -k secretcats_watch
-a always,exit -F arch=b64 -S openat -F auid=1006
[donnie@localhost ~]$</code></pre>
</div>
<p>Here's the breakdown:</p>
<ul>
<li><code>-a always,exit</code>: Here, we have the action and the list. The <code>exit</code> part means that this rule will be added to the system call <code>exit</code> list. Whenever the operating system exits from a system call, the <code>exit</code> list will be used to determine if an audit event needs to be generated. The <code>always</code> part is the action, which means that an audit record for this rule will always be created on exit from the specified system call. Note that the action and list parameters have to be separated by a comma.</li>
<li><code>-F arch=b64</code>: The <code>-F</code> option is used to build a rule field, and we can see two rule fields in this command. This first rule field specifies the machine's CPU architecture. <code>b64</code> means that the computer is running with an x86_64 CPU. (Whether it's Intel or AMD doesn't matter.) Considering that 32-bit machines are dying off and that Sun SPARC and PowerPC machines aren't all that common, <code>b64</code> is what you'll now mostly see.</li>
<li><code>-S openat</code>: The <code>-S</code> option specifies the system call that we want to monitor. <code>openat</code> is the system call that either opens or creates a file.</li>
<li><code>-F auid=1006</code>: This second audit field specifies the user ID number of the user that we want to monitor. (Charlie's user ID number is <code>1006</code>.)</li>
</ul>
<blockquote>
<p>A complete explanation of system calls, or syscalls, is a bit too esoteric for our present purpose. For now, suffice it to say that a syscall happens whenever a user issues a command that requests that the Linux kernel provide a service. If you're so inclined, you can read more about syscalls at <a href="https://blog.packagecloud.io/eng/2016/04/05/the-definitive-guide-to-linux-system-calls/">https://blog.packagecloud.io/eng/2016/04/05/the-definitive-guide-to-linux-system-calls/</a>.</p>
</blockquote>
<p>What I've presented here are just a few of the many things that you can do with auditing rules. To see more examples, check out the <code>auditctl</code> man page:</p>
<div><pre><code>man auditctl</code></pre>
</div>
<p>So, now you're wondering, <em>Now that I have these rules, how do I know when someone tries to violate them?</em> As always, I'm glad that you asked.</p>



<h2 data-number="13.7">Using ausearch and aureport</h2>
<p>The <code>auditd</code> daemon logs events to the <code>/var/log/audit/audit.log</code> file. Although you could directly read the file with something such as <code>less</code>, you really don't want to. The <code>ausearch</code> and <code>aureport</code> utilities will help you translate the file into a language that makes some sort of sense.</p>

<h3 data-number="13.7.1">Searching for file change alerts</h3>
<p>Let's start by looking at the rule that we created that will alert us whenever a change is made to the <code>/etc/passwd</code> file:</p>
<div><pre><code>sudo auditctl -w /etc/passwd -p wa -k passwd_changes</code></pre>
</div>
<p>Now, let's make a change to the file and look for the alert message. Rather than add another user, since I'm running out of cats whose names I can use, I'll just use the <code>chfn</code> utility to add contact information to the comment field for Cleopatra's entry:</p>
<div><pre><code>[donnie@localhost etc]$ sudo chfn cleopatra
Changing finger information for cleopatra.
Name []: Cleopatra Tabby Cat
Office []: Donnie&#39;s back yard
Office Phone []: 555-5555
Home Phone []: 555-5556
Finger information changed.
[donnie@localhost etc]</code></pre>
</div>
<p>Now, I'll use <code>ausearch</code> to look for any audit messages that this event may have generated:</p>
<div><pre><code>[donnie@localhost ~]$ sudo ausearch -i -k passwd_changes
----
type=CONFIG_CHANGE msg=audit(12/11/2017 13:06:20.665:11393) : auid=donnie ses=842 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 op=add_rule key=passwd_changes li
st=exit res=yes
----
type=CONFIG_CHANGE msg=audit(12/11/2017 13:49:15.262:11511) : auid=donnie ses=842 op=updated_rules path=/etc/passwd key=passwd_changes list=exit res=yes
[donnie@localhost ~]$</code></pre>
</div>
<p>Here's the breakdown:</p>
<ul>
<li><code>-i</code>: This takes any numeric data and, whenever possible, converts it into text. In this case, it takes user ID numbers and converts them into the actual username, which shows up here as <code>auid=donnie</code>. If I were to leave the <code>-i</code> out, the user information would show up as <code>auid=1000</code>, which is my user ID number.</li>
<li><code>-k passwd_changes</code>: This specifies the key, or the name, of the audit rule for which we want to see the audit messages.</li>
</ul>
<p>Here, you see that there are two parts to this output. The first part just shows when I created the audit rule, so we're not interested in that. In the second part, you can see when I triggered the rule, but it doesn't show how I triggered it. So, let's use <code>aureport</code> to see whether it will give us a bit more detail:</p>
<div><pre><code>[donnie@localhost ~]$ sudo aureport -i -k | grep &#39;passwd_changes&#39;
1. 12/11/2017 13:06:20 passwd_changes yes ? donnie 11393
2. 12/11/2017 13:49:15 passwd_changes yes ? donnie 11511
3. 12/11/2017 13:49:15 passwd_changes yes /usr/bin/chfn donnie 11512
4. 12/11/2017 14:54:11 passwd_changes yes /usr/sbin/usermod donnie 11728
5. 12/11/2017 14:54:25 passwd_changes yes /usr/sbin/usermod donnie 11736
[donnie@localhost ~]$</code></pre>
</div>
<p>What's curious is that with <code>ausearch</code>, you have to specify the name, or key, of the audit rule that interests you after the <code>-k</code> option. With <code>aureport</code>, the <code>-k</code> option means that you want to look at all log entries that have to do with all audit rule keys. To see log entries for a specific key, just pipe the output into <code>grep</code>. The <code>-i</code> option does the same thing that it does for <code>ausearch</code>.</p>
<p>As you see, <code>aureport</code> parses the cryptic language of the <code>audit.log</code> file into plain language that's easier to understand. I wasn't sure about what I had done to generate events 1 and 2, so I looked in the <code>/var/log/secure</code> file to see whether I could find out. I saw these two entries for those times:</p>
<div><pre><code>Dec 11 13:06:20 localhost sudo: donnie : TTY=pts/1 ; PWD=/home/donnie ; USER=root ; COMMAND=/sbin/auditctl -w /etc/passwd -p wa -k passwd_changes
. . .
. . .
Dec 11 13:49:24 localhost sudo: donnie : TTY=pts/1 ; PWD=/home/donnie ; USER=root ; COMMAND=/sbin/ausearch -i -k passwd_changes</code></pre>
</div>
<p>So, event 1 was from when I initially created the audit rule, and event 2 happened when I did an <code>ausearch</code> operation.</p>
<p>I must confess that the events in lines <em>4</em> and <em>5</em> are a bit of a mystery. Both were created when I invoked the <code>usermod</code> command, and both of them correlate to the secure log entries where I added Vicky and Cleopatra to the <code>secretcats</code> group:</p>
<div><pre><code>Dec 11 14:54:11 localhost sudo:  donnie : TTY=pts/1 ; PWD=/home/donnie ; USER=root ; COMMAND=/sbin/usermod -a -G secretcats vicky
Dec 11 14:54:11 localhost usermod[14865]: add &#39;vicky&#39; to group &#39;secretcats&#39;
Dec 11 14:54:11 localhost usermod[14865]: add &#39;vicky&#39; to shadow group &#39;secretcats&#39;
Dec 11 14:54:25 localhost sudo:  donnie : TTY=pts/1 ; PWD=/home/donnie ; USER=root ; COMMAND=/sbin/usermod -a -G secretcats cleopatra
Dec 11 14:54:25 localhost usermod[14871]: add &#39;cleopatra&#39; to group &#39;secretcats&#39;
Dec 11 14:54:25 localhost usermod[14871]: add &#39;cleopatra&#39; to shadow group &#39;secretcats&#39;</code></pre>
</div>
<p>The strange part about this is that adding a user to a secondary group doesn't modify the <code>passwd</code> file. So, I really don't know why the rule was triggered to create the events in lines <em>4</em> and <em>5</em>.</p>
<p>This leaves us with the event in line <em>3</em>, which is where I used <code>chfn</code> to actually modify the <code>passwd</code> file. Here's the <code>secure</code> log entry for that:</p>
<div><pre><code>Dec 11 13:48:49 localhost sudo:  donnie : TTY=pts/1 ; PWD=/etc ; USER=root ; COMMAND=/bin/chfn cleopatra</code></pre>
</div>
<p>So, out of all of these events, the one in line <em>3</em> is the only one where the <code>/etc/passwd</code> file was actually modified.</p>
<blockquote>
<p>The <code>/var/log/secure</code> file that I keep mentioning here is on Red Hat-type operating systems, such as CentOS and AlmaLinux. On your Ubuntu machine, you'll see the <code>/var/log/auth.log</code> file instead.</p>
</blockquote>


<h3 data-number="13.7.2">Searching for directory access rule violations</h3>
<p>For our next scenario, we’ll create a shared directory for Vicky and Cleopatra and then create an audit rule for it that looks like this:</p>
<div><pre><code>sudo auditctl -w /secretcats/ -k secretcats_watch</code></pre>
</div>
<p>So, all access or attempted access to this directory should trigger an alert. First, let's have Vicky enter the <code>/secretcats/</code> directory and run an <code>ls -l</code> command:</p>
<div><pre><code>[vicky@localhost ~]$ cd /secretcats
[vicky@localhost secretcats]$ ls -l
total 4
-rw-rw-r--. 1 cleopatra secretcats 31 Dec 12 11:49 cleopatrafile.txt
[vicky@localhost secretcats]$</code></pre>
</div>
<p>Here, we see that Cleopatra has already been there and has created a file. (We'll get back to that in a moment.) When an event triggers an <code>auditd</code> rule, it often creates multiple records in the <code>/var/log/audit/audit.log</code> file. If you look through each record for an event, you'll see that each one covers a different aspect of that event. When I do an <code>ausearch</code> command, I see a total of five records just from that one <code>ls -l</code> operation. For the sake of saving space, I'll just put the first one here:</p>
<div><pre><code>sudo ausearch -i -k secretcats_watch | less
type=PROCTITLE msg=audit(12/12/2017 12:15:35.447:14077) : proctitle=ls --color=auto -l
type=PATH msg=audit(12/12/2017 12:15:35.447:14077) : item=0 name=. inode=33583041 dev=fd:01 mode=dir,sgid,sticky,770 ouid=nobody ogid=secretcats rdev=00:00 obj=unconfined_u:object_r:default_t:s0 objtype=NORMAL
type=CWD msg=audit(12/12/2017 12:15:35.447:14077) :  cwd=/secretcats
type=SYSCALL msg=audit(12/12/2017 12:15:35.447:14077) : arch=x86_64 syscall=openat success=yes exit=3 a0=0xffffffffffffff9c a1=0x2300330 a2=O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC a3=0x0 items=1 ppid=10805 pid=10952 auid=vicky uid=vicky gid=vicky euid=vicky suid=vicky fsuid=vicky egid=vicky sgid=vicky fsgid=vicky tty=pts0 ses=1789 comm=ls exe=/usr/bin/ls subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=secretcats_watch</code></pre>
</div>
<p>I'll put the last one here:</p>
<div><pre><code>type=PROCTITLE msg=audit(12/12/2017 12:15:35.447:14081) : proctitle=ls --color=auto -l
type=PATH msg=audit(12/12/2017 12:15:35.447:14081) : item=0 name=cleopatrafile.txt inode=33583071 dev=fd:01 mode=file,664 ouid=cleopatra ogid=secretcats rdev=00:00 obj=unconfined_u:object_r:default_t:s0 objtype=NORMAL
type=CWD msg=audit(12/12/2017 12:15:35.447:14081) :  cwd=/secretcats
type=SYSCALL msg=audit(12/12/2017 12:15:35.447:14081) : arch=x86_64 syscall=getxattr success=no exit=ENODATA(No data available) a0=0x7fff7c266e60 a1=0x7f0a61cb9db0 a2=0x0 a3=0x0 items=1 ppid=10805 pid=10952 auid=vicky uid=vicky gid=vicky euid=vicky suid=vicky fsuid=vicky egid=vicky sgid=vicky fsgid=vicky tty=pts0 ses=1789 comm=ls exe=/usr/bin/ls subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=secretcats_watch</code></pre>
</div>
<p>In both records, you see the action that was taken (<code>ls -l</code>) and information about the person – or cat, in this case – that took the action. Since this is a RHEL-type machine, you also see SELinux context information. In the second record, you can also see the name of the file that Vicky saw when she did the <code>ls</code> command.</p>
<p>Next, let's say that that sneaky Charlie guy logs in and tries to get into the <code>/secretcats/</code> directory:</p>
<div><pre><code>[charlie@localhost ~]$ cd /secretcats
-bash: cd: /secretcats: Permission denied
[charlie@localhost ~]$ ls -l /secretcats
ls: cannot open directory /secretcats: Permission denied
[charlie@localhost ~]$</code></pre>
</div>
<p>Charlie isn't a member of the <code>secretcats</code> group and doesn't have permission to go into the <code>secretcats</code> directory. So, he should trigger an alert message. Well, he actually triggered one that consists of four records, and I'll again just list the first one and the last one. Here's the first one:</p>
<div><pre><code>sudo ausearch -i -k secretcats_watch | less
type=PROCTITLE msg=audit(12/12/2017 12:32:04.341:14152) : proctitle=ls --color=auto -l /secretcats
type=PATH msg=audit(12/12/2017 12:32:04.341:14152) : item=0 name=/secretcats inode=33583041 dev=fd:01 mode=dir,sgid,sticky,770 ouid=nobody ogid=secretcats rdev=00:00 obj=unconfined_u:object_r:default_t:s0 objtype=NORMAL
type=CWD msg=audit(12/12/2017 12:32:04.341:14152) :  cwd=/home/charlie
type=SYSCALL msg=audit(12/12/2017 12:32:04.341:14152) : arch=x86_64 syscall=lgetxattr success=yes exit=35 a0=0x7ffd8d18f7dd a1=0x7f2496858f8a a2=0x12bca30 a3=0xff items=1 ppid=11637 pid=11663 auid=charlie uid=charlie gid=charlie euid=charlie suid=charlie fsuid=charlie egid=charlie sgid=charlie fsgid=charlie tty=pts0 ses=1794 comm=ls exe=/usr/bin/ls subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=secretcats_watch</code></pre>
</div>
<p>Here's the last one:</p>
<div><pre><code>type=PROCTITLE msg=audit(12/12/2017 12:32:04.341:14155) : proctitle=ls --color=auto -l /secretcats
type=PATH msg=audit(12/12/2017 12:32:04.341:14155) : item=0 name=/secretcats inode=33583041 dev=fd:01 mode=dir,sgid,sticky,770 ouid=nobody ogid=secretcats rdev=00:00 obj=unconfined_u:object_r:default_t:s0 objtype=NORMAL
type=CWD msg=audit(12/12/2017 12:32:04.341:14155) :  cwd=/home/charlie
type=SYSCALL msg=audit(12/12/2017 12:32:04.341:14155) : arch=x86_64 syscall=openat success=no exit=EACCES(Permission denied) a0=0xffffffffffffff9c a1=0x12be300 a2=O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC a3=0x0 items=1 ppid=11637 pid=11663 auid=charlie uid=charlie gid=charlie euid=charlie suid=charlie fsuid=charlie egid=charlie sgid=charlie fsgid=charlie tty=pts0 ses=1794 comm=ls exe=/usr/bin/ls subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=secretcats_watch</code></pre>
</div>
<p>There are two things to note here. First, just attempting to <code>cd</code> into the directory doesn't trigger an alert. However, using <code>ls</code> to try to read the contents of the directory does. Secondly, note the <code>Permission denied</code> message that shows up in the second record.</p>
<p>The last set of alerts that we'll look at were created when Cleopatra created her <code>cleopatrafile.txt</code> file. This event triggered an alert that consists of 30 records. I'll just show you two of them, with the first one here:</p>
<div><pre><code>type=PROCTITLE msg=audit(12/12/2017 11:49:37.536:13856) : proctitle=vim cleopatrafile.txt
type=PATH msg=audit(12/12/2017 11:49:37.536:13856) : item=0 name=. inode=33583041 dev=fd:01 mode=dir,sgid,sticky,770 ouid=nobody ogid=secretcats rdev=00:00 obj=unconfined_u:o
bject_r:default_t:s0 objtype=NORMAL
type=CWD msg=audit(12/12/2017 11:49:37.536:13856) :  cwd=/secretcats
type=SYSCALL msg=audit(12/12/2017 11:49:37.536:13856) : arch=x86_64 syscall=open success=yes exit=4 a0=0x5ab983 a1=O_RDONLY a2=0x0 a3=0x63 items=1 ppid=9572 pid=9593 auid=cle
opatra uid=cleopatra gid=cleopatra euid=cleopatra suid=cleopatra fsuid=cleopatra egid=cleopatra sgid=cleopatra fsgid=cleopatra tty=pts0 ses=1779 comm=vim exe=/usr/bin/vim sub
j=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=secretcats_watch</code></pre>
</div>
<p>Here’s the second one:</p>
<div><pre><code>type=PROCTITLE msg=audit(12/12/2017 11:49:56.001:13858) : proctitle=vim cleopatrafile.txt
type=PATH msg=audit(12/12/2017 11:49:56.001:13858) : item=1 name=/secretcats/.cleopatrafile.txt.swp inode=33583065 dev=fd:01 mode=file,600 ouid=cleopatra ogid=secretcats rdev
=00:00 obj=unconfined_u:object_r:default_t:s0 objtype=DELETE
type=PATH msg=audit(12/12/2017 11:49:56.001:13858) : item=0 name=/secretcats/ inode=33583041 dev=fd:01 mode=dir,sgid,sticky,770 ouid=nobody ogid=secretcats rdev=00:00 obj=unc
onfined_u:object_r:default_t:s0 objtype=PARENT
type=CWD msg=audit(12/12/2017 11:49:56.001:13858) :  cwd=/secretcats
type=SYSCALL msg=audit(12/12/2017 11:49:56.001:13858) : arch=x86_64 syscall=unlink success=yes exit=0 a0=0x15ee7a0 a1=0x1 a2=0x1 a3=0x7ffc2c82e6b0 items=2 ppid=9572 pid=9593
auid=cleopatra uid=cleopatra gid=cleopatra euid=cleopatra suid=cleopatra fsuid=cleopatra egid=cleopatra sgid=cleopatra fsgid=cleopatra tty=pts0 ses=1779 comm=vim exe=/usr/bin
/vim subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=secretcats_watch</code></pre>
</div>
<p>You can tell that the first of these two messages happened when Cleopatra saved the file and exited <code>vim</code> because the second message shows <code>objtype=DELETE</code>, where her temporary <code>vim</code> swap file was deleted.</p>
<p>Okay, this is all good, but what if this is too much information? What if you just want a quick and sparse list of all of the security events that got triggered by this rule? For that, we'll use <code>aureport</code>. We'll use it just like we did previously.</p>
<p>First, let's pipe the <code>aureport</code> output into <code>less</code> instead of into <code>grep</code> so that we can see the column headers:</p>
<div><pre><code>[donnie@localhost ~]$ sudo aureport -i -k | less
Key Report
===============================================
# date time key success exe auid event
===============================================
1. 12/11/2017 13:06:20 passwd_changes yes ? donnie 11393
2. 12/11/2017 13:49:15 passwd_changes yes ? donnie 11511
3. 12/11/2017 13:49:15 passwd_changes yes /usr/bin/chfn donnie 11512
4. 12/11/2017 14:54:11 passwd_changes yes /usr/sbin/usermod donnie 11728
5. 12/11/2017 14:54:25 passwd_changes yes /usr/sbin/usermod donnie 11736
. . .
. . .</code></pre>
</div>
<p>The status in the <code>success</code> column will be either <code>yes</code> or <code>no</code>, depending upon whether the user was able to successfully perform an action that violated a rule. Or, it could be a question mark if the event isn't the result of the rule being triggered.</p>
<p>For Charlie, we see a <code>yes</code> event in line <em>48</em>, with the events in lines <em>49</em> through <em>51</em> all having a <code>no</code> status. We can also see that all of these entries were triggered by Charlie's use of the <code>ls</code> command:</p>
<p>[donnie@localhost ~]$ sudo aureport -i -k | grep 'secretcats_watch'</p>
<p>6. 12/11/2017 15:01:25 secretcats_watch yes ? donnie 11772</p>
<p>8. 12/12/2017 11:49:29 secretcats_watch yes /usr/bin/ls cleopatra 13828</p>
<p>9. 12/12/2017 11:49:37 secretcats_watch yes /usr/bin/vim cleopatra 13830</p>
<p>10. 12/12/2017 11:49:37 secretcats_watch yes /usr/bin/vim cleopatra 13829</p>
<div><p>48. 12/12/2017 12:32:04 secretcats_watch yes /usr/bin/ls charlie 14152</p>
<p>49. 12/12/2017 12:32:04 secretcats_watch no /usr/bin/ls charlie 14153</p>
<p>50. 12/12/2017 12:32:04 secretcats_watch no /usr/bin/ls charlie 14154</p>
<p>51. 12/12/2017 12:32:04 secretcats_watch no /usr/bin/ls charlie 14155</p>
<p>[donnie@localhost ~]$</p>
<p>You'd be tempted to think that the <code>yes</code> event in line <em>48</em> indicates that Charlie was successful in reading the contents of the <code>secretcats</code> directory. To analyze this further, let's look at the event numbers at the end of each line and correlate them to the output of our previous <code>ausearch</code> command. You'll see that event numbers <code>14152</code> through <code>14155</code> belong to records that all have the same timestamp. We can see this in the first line of each record:</p>
<div><pre><code>[donnie@localhost ~]$ sudo ausearch -i -k secretcats_watch | less
type=PROCTITLE msg=audit(12/12/2017 12:32:04.341:14152) : proctitle=ls --color=auto -l /secretcats
type=PROCTITLE msg=audit(12/12/2017 12:32:04.341:14153) : proctitle=ls --color=auto -l /secretcats
type=PROCTITLE msg=audit(12/12/2017 12:32:04.341:14154) : proctitle=ls --color=auto -l /secretcats
type=PROCTITLE msg=audit(12/12/2017 12:32:04.341:14155) : proctitle=ls --color=auto -l /secretcats</code></pre>
</div>
<p>As we noted previously, the last record of this series shows <code>Permission denied</code> for Charlie, and that's what really counts.</p>
<blockquote>
<p>Space doesn't permit me to give a full explanation of each individual item in an audit log record. However, you can read about it here, in the official Red Hat documentation: <a href="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/security_hardening/auditing-the-system_security-hardening#understanding-audit-log-files_auditing-the-system">https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/security_hardening/auditing-the-system_security-hardening#understanding-audit-log-files_auditing-the-system</a>.</p>
</blockquote>
</div>


<h3 data-number="13.7.3">Searching for system call rule violations</h3>
<p>The third rule that we created was to monitor that sneaky Charlie. This rule will alert us whenever Charlie tries to open or create a file. (As we noted previously, <code>1006</code> is Charlie's user ID number.):</p>
<div><pre><code>sudo auditctl -a always,exit -F arch=b64 -S openat -F auid=1006</code></pre>
</div>
<p>Even though Charlie hasn't done that much on this system, this rule gives us a lot more log entries than what we bargained for. We'll look at just a couple of entries:</p>
<div><pre><code>time-&gt;Tue Dec 12 11:49:29 2017
type=PROCTITLE msg=audit(1513097369.952:13828): proctitle=6C73002D2D636F6C6F723D6175746F
type=PATH msg=audit(1513097369.952:13828): item=0 name=&quot;.&quot; inode=33583041 dev=fd:01 mode=043770 ouid=99 ogid=1009 rdev=00:00 obj=unconfined_u:object_r:default_t:s0 objtype=NO
RMAL
type=CWD msg=audit(1513097369.952:13828):  cwd=&quot;/secretcats&quot;
type=SYSCALL msg=audit(1513097369.952:13828): arch=c000003e syscall=257 success=yes exit=3 a0=ffffffffffffff9c a1=10d1560 a2=90800 a3=0 items=1 ppid=9572 pid=9592 auid=1004 u
id=1004 gid=1006 euid=1004 suid=1004 fsuid=1004 egid=1006 sgid=1006 fsgid=1006 tty=pts0 ses=1779 comm=&quot;ls&quot; exe=&quot;/usr/bin/ls&quot; subj=unconfined_u:unconfined_r:unconfined_t:s0-s0
:c0.c1023 key=&quot;secretcats_watch&quot;</code></pre>
</div>
<p>This record was generated when Charlie tried to access the <code>/secretcats/</code> directory. So, we can expect to see this one. But, what we didn't expect to see was the exceedingly long list of records of files that Charlie indirectly accessed when he logged into the system through <strong>Secure Shell</strong> (<strong>SSH</strong>). Here's one:</p>
<div><pre><code>time-&gt;Tue Dec 12 11:50:28 2017
type=PROCTITLE msg=audit(1513097428.662:13898): proctitle=737368643A20636861726C6965407074732F30
type=PATH msg=audit(1513097428.662:13898): item=0 name=&quot;/proc/9726/fd&quot; inode=1308504 dev=00:03 mode=040500 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:unconfined_r:unconfined_t
:s0-s0:c0.c1023 objtype=NORMAL
type=CWD msg=audit(1513097428.662:13898):  cwd=&quot;/home/charlie&quot;
type=SYSCALL msg=audit(1513097428.662:13898): arch=c000003e syscall=257 success=yes exit=3 a0=ffffffffffffff9c a1=7ffc7ca1d840 a2=90800 a3=0 items=1 ppid=9725 pid=9726 auid=1
006 uid=1006 gid=1008 euid=1006 suid=1006 fsuid=1006 egid=1008 sgid=1008 fsgid=1008 tty=pts0 ses=1781 comm=&quot;sshd&quot; exe=&quot;/usr/sbin/sshd&quot; subj=unconfined_u:unconfined_r:unconfin
ed_t:s0-s0:c0.c1023 key=(null)</code></pre>
</div>
<p>Here's another one:</p>
<div><pre><code>time-&gt;Tue Dec 12 11:50:28 2017
type=PROCTITLE msg=audit(1513097428.713:13900): proctitle=737368643A20636861726C6965407074732F30
type=PATH msg=audit(1513097428.713:13900): item=0 name=&quot;/etc/profile.d/&quot; inode=33593031 dev=fd:01 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:bin_t:s0 objtype=
NORMAL
type=CWD msg=audit(1513097428.713:13900):  cwd=&quot;/home/charlie&quot;
type=SYSCALL msg=audit(1513097428.713:13900): arch=c000003e syscall=257 success=yes exit=3 a0=ffffffffffffff9c a1=1b27930 a2=90800 a3=0 items=1 ppid=9725 pid=9726 auid=1006 u
id=1006 gid=1008 euid=1006 suid=1006 fsuid=1006 egid=1008 sgid=1008 fsgid=1008 tty=pts0 ses=1781 comm=&quot;bash&quot; exe=&quot;/usr/bin/bash&quot; subj=unconfined_u:unconfined_r:unconfined_t:s
0-s0:c0.c1023 key=(null)</code></pre>
</div>
<p>In the first record, we see that Charlie accessed the <code>/usr/sbin/sshd</code> file. In the second, we see that he accessed the <code>/usr/bin/bash</code> file. It's not that Charlie chose to access those files. The operating system accessed those files for him in the course of just a normal login event. So as you see, when you create audit rules, you have to be careful what you wish for because there's a definite danger that the wish might be granted. If you really need to monitor someone, you'll want to create a rule that won't give you quite this much information.</p>
<p>While we're at it, we might as well see what the <code>aureport</code> output for this looks like:</p>
<div><pre><code>[donnie@localhost ~]$ sudo aureport -s -i | grep &#39;openat&#39;
1068. 12/12/2017 11:49:29 openat 9592 ls cleopatra 13828
1099. 12/12/2017 11:50:28 openat 9665 sshd charlie 13887
1100. 12/12/2017 11:50:28 openat 9665 sshd charlie 13889
1101. 12/12/2017 11:50:28 openat 9665 sshd charlie 13890
1102. 12/12/2017 11:50:28 openat 9726 sshd charlie 13898
1103. 12/12/2017 11:50:28 openat 9726 bash charlie 13900
1104. 12/12/2017 11:50:28 openat 9736 grep charlie 13901
1105. 12/12/2017 11:50:28 openat 9742 grep charlie 13902
1108. 12/12/2017 11:50:51 openat 9766 ls charlie 13906
1110. 12/12/2017 12:15:35 openat 10952 ls vicky 14077
1115. 12/12/2017 12:30:54 openat 11632 sshd charlie 14129
. . .
. . .</code></pre>
</div>
<p>In addition to what Charlie did, we also see what Vicky and Cleopatra did. That's because the rule that we set for the <code>/secretcats/</code> directory generated <code>openat</code> events when Vicky and Cleopatra accessed, viewed, or created files in that directory.</p>


<h3 data-number="13.7.4">Generating authentication reports</h3>
<p>You can generate user authentication reports without having to define any audit rules. Just use <code>aureport</code> with the <code>-au</code> option switch. (Remember <code>au</code>, the first two letters of <em>authentication</em>.):</p>
<div><pre><code>[donnie@localhost ~]$ sudo aureport -au
[sudo] password for donnie:
Authentication Report
============================================
# date time acct host term exe success event
============================================
1. 10/28/2017 13:38:52 donnie localhost.localdomain tty1 /usr/bin/login yes 94
2. 10/28/2017 13:39:03 donnie localhost.localdomain /dev/tty1 /usr/bin/sudo yes 102
3. 10/28/2017 14:04:51 donnie localhost.localdomain /dev/tty1 /usr/bin/sudo yes 147
. . .
. . .
239. 12/12/2017 11:50:20 charlie 192.168.0.222 ssh /usr/sbin/sshd no 13880
244. 12/12/2017 12:10:06 cleopatra 192.168.0.222 ssh /usr/sbin/sshd no 13992
. . .</code></pre>
</div>
<p>For login events, this tells us whether the user logged in at the local terminal or remotely through SSH. To see the details of any event, use <code>ausearch</code> with the <code>-a</code> option, followed by the event number that you see at the end of a line. (Strangely, the <code>-a</code> option stands for an <em>event</em>.)</p>
<p>Let's look at event number <code>14122</code> for Charlie:</p>
<div><pre><code>[donnie@localhost ~]$ sudo ausearch -a 14122
----
time-&gt;Tue Dec 12 12:30:49 2017
type=USER_AUTH msg=audit(1513099849.322:14122): pid=11632 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg=&#39;op=pubkey acct=&quot;charlie&quot; exe=&quot;/usr/sbin/sshd&quot; hostname=? addr=192.168.0.222 terminal=ssh res=failed&#39;</code></pre>
</div>
<p>The problem with this is that it really doesn't make any sense. I'm the one who did the logins for Charlie, and I know for a fact that Charlie never had any failed logins. In fact, we can correlate this with the matching entry from the <code>/var/log/secure</code> file:</p>
<div><pre><code>Dec 12 12:30:53 localhost sshd[11632]: Accepted password for charlie from 192.168.0.222 port 34980 ssh2
Dec 12 12:30:54 localhost sshd[11632]: pam_unix(sshd:session): session opened for user charlie by (uid=0)</code></pre>
</div>
<p>The timestamps for these two entries are a few seconds later than the timestamp for the <code>ausearch</code> output, but that's okay. There's nothing in this log file to suggest that Charlie ever had a failed login, and these two entries clearly show that Charlie's login really was successful. The lesson here is that when you see something strange in either the <code>ausearch</code> or <code>aureport</code> output, be sure to correlate it with the matching entry in the proper authentication log file to get a better idea of what's going on. (By authentication log file, I mean <code>/var/log/secure</code> for Red Hat-type systems and <code>/var/log/auth.log</code> for Ubuntu systems. The names may vary for other Linux distros.)</p>


<h3 data-number="13.7.5">Using pre-defined rulesets</h3>
<p>In the <code>/usr/share/doc/audit-version_number/rules/</code> directory of your CentOS 7 machine and the <code>/usr/share/audit/sample-rules/</code> directory of your AlmaLinux machines, you'll see some pre-made rulesets for different scenarios. Once you install <code>auditd</code> on Ubuntu, you'll have audit rules in the <code>/usr/share/doc/auditd/examples/rules/</code> directory. In any case, some of the rulesets are common among all three of these distros. Let's look at the AlmaLinux 9 machine to see what we have there:</p>
<div><pre><code>[donnie@localhost ~]$ cd /usr/share/audit/sample-rules/
[donnie@localhost sample-rules]$ ls -l
total 160
. . .
-rw-r--r--. 1 root root 4943 Oct 27 07:15 30-nispom.rules
. . .
-rw-r--r--. 1 root root 6179 Oct 27 07:15 30-pci-dss-v31.rules
-rw-r--r--. 1 root root 6624 Oct 27 07:15 30-stig.rules
-rw-r--r--. 1 root root 1458 Oct 27 07:15 31-privileged.rules
-rw-r--r--. 1 root root  213 Oct 27 07:15 32-power-abuse.rules
. . .
[donnie@localhost sample-rules]$</code></pre>
</div>
<p>The three files I want to focus on are the <code>nispom</code>, <code>pci-dss</code>, and <code>stig</code> files. Each of these three rulesets is designed to meet the auditing standards of a particular certifying agency. In order, these rulesets are:</p>
<ul>
<li><strong>nispom</strong>: The National Industrial Security Program – you'll see this ruleset used at either the US Department of Defense or its contractors.</li>
<li><strong>pci-dss</strong>: Payment Card Industry Data Security Standard – if you work in the banking or financial industries, or even if you're just running an online business that accepts credit cards, you'll likely become very familiar with this.</li>
<li><strong>stig</strong>: Security Technical Implementation Guides – if you work for the US government, or possibly other governments, you'll be dealing with this one.</li>
</ul>
<p>To use one of these rules sets, just copy the appropriate files over to the <code>/etc/audit/rules.d/</code> directory:</p>
<div><pre><code>[donnie@localhost rules]$ sudo cp 30-pci-dss-v31.rules /etc/audit/rules.d
[donnie@localhost rules]$</code></pre>
</div>
<p>After you've copied the rule file over, restart the <code>auditd</code> daemon to read in the new rules.</p>
<p>For Red Hat, CentOS, or AlmaLinux, do this:</p>
<div><pre><code>sudo service auditd restart</code></pre>
</div>
<p>For Ubuntu, do this:</p>
<div><pre><code>sudo systemctl restart auditd</code></pre>
</div>
<p>Of course, there's always the chance that a particular rule in one of these sets might not work for you or that you might need to enable a rule that's currently disabled. If so, just open the appropriate rules file in your text editor and comment out what doesn't work or uncomment what you need to enable.</p>
<p>Even though <code>auditd</code> is very cool, bear in mind that it only alerts you about potential security breaches. It doesn't do anything to harden the system against them.</p>


<h3 data-number="13.7.6">Hands-on lab – using auditd</h3>
<p>In this lab, you'll practice using the features of <code>auditd</code>. Let's get started:</p>
<ol>
<li>For Ubuntu only, install <code>auditd</code>:</li>
</ol>
<div><pre><code>sudo apt update
sudo apt install auditd</code></pre>
</div>
<ol>
<li>View the rules that are currently in effect:</li>
</ol>
<div><pre><code>sudo auditctl -l</code></pre>
</div>
<ol>
<li>From the command line, create a temporary rule that audits the <code>/etc/passwd</code> file for changes. Verify that the rule is in effect:</li>
</ol>
<div><pre><code>sudo auditctl -w /etc/passwd -p wa -k passwd_changes
sudo auditctl -l</code></pre>
</div>
<ol>
<li>Create a user account for Lionel. On Ubuntu, do this:</li>
</ol>
<div><pre><code>sudo adduser lionel</code></pre>
</div>
<ol>
<li>On CentOS or AlmaLinux, do this:</li>
</ol>
<div><pre><code>sudo useradd lionel
sudo passwd lionel</code></pre>
</div>
<ol>
<li>Search for audit messages regarding any changes to the <code>passwd</code> file:</li>
</ol>
<div><pre><code>sudo ausearch -i -k passwd_changes
sudo aureport -i -k | grep &#39;passwd_changes&#39;</code></pre>
</div>
<ol>
<li>Log out of your own account and log in as Lionel. Then, log out of Lionel's account and back in to your own.</li>
<li>Do an authentication report:</li>
</ol>
<div><pre><code>sudo aureport -au</code></pre>
</div>
<ol>
<li>Create the <code>/secrets</code> directory and set the permissions so that only the root user can access it:</li>
</ol>
<div><pre><code>sudo mkdir /secrets
sudo chmod 700 /secrets</code></pre>
</div>
<ol>
<li>Create a rule that monitors the <code>/secrets</code> directory:</li>
</ol>
<div><pre><code>sudo auditctl -w /secrets -k secrets_watch
sudo auditctl -l</code></pre>
</div>
<ol>
<li>Log out of your account, and log in as Lionel. Have him try to view what's in the <code>/secrets</code> directory:</li>
</ol>
<div><pre><code>ls -l /secrets</code></pre>
</div>
<ol>
<li>Log out of Lionel's account and log in to your own. View the alerts that Lionel created:</li>
</ol>
<div><pre><code>sudo ausearch -i -k secrets_watch | less</code></pre>
</div>
<ol>
<li>You now have two temporary rules that will disappear when you reboot the machine. Make them permanent by creating a <code>custom.rules</code> file:</li>
</ol>
<div><pre><code>sudo sh -c &quot;auditctl -l &gt; /etc/audit/rules.d/custom.rules&quot;</code></pre>
</div>
<ol>
<li>Reboot the machine and verify that the rules are still in effect:</li>
</ol>
<div><pre><code>sudo auditctl -l</code></pre>
</div>
<p>You've reached the end of the lab – congratulations!</p>


<h3 data-number="13.7.7">Hands-on lab –Using pre-configured rules with auditd</h3>
<p>In this lab, we’ll simulate that the US government is our client, and that we need to set up a server that will meet their <strong>Security Technical Implementation Guides</strong> (<strong>STIG</strong>) auditing standards. To do that, we’ll use several pre-configured rulesets that get installed when you install <code>auditd</code>. Note that this lab will work on any of your virtual machines:</p>
<ol>
<li>Delete the <code>custom.rules</code> file that you created in the previous lab, and then restart the <code>auditd</code> service.</li>
<li>Copy the <code>10-base-config.rules</code>, <code>30-stig.rules</code>, <code>31-privileged.rules</code>, and <code>99-finalize.rules</code> files to the <code>/etc/audit/rules.d/</code> directory. (These rules files are in the <code>/usr/share/doc/auditd/examples/rules/</code> directory on Ubuntu, and in the <code>/usr/share/audit/sample-rules/</code> directory on AlmaLinx.):</li>
</ol>
<div><pre><code>[donnie@almalinux9 sample-rules]$ pwd
/usr/share/audit/sample-rules
[donnie@almalinux9 sample-rules]$ sudo cp 10-base-config.rules 30-stig.rules 31-privileged.rules 99-finalize.rules /etc/audit/rules.d
[donnie@almalinux9 sample-rules]$</code></pre>
</div>
<ol>
<li>Restart the <code>auditd</code> service, and then use <code>sudo auditctl -l</code> to view the new active ruleset.</li>
<li>End of lab.</li>
</ol>
<blockquote>
<p>You’ve just seen that we can sometimes use several different pre-configured rulesets at once <em>if</em> they complement each other. Understand though that you’ll never use <em>all</em> of the pre-configured rulesets at once.</p>
</blockquote>
<p>In this section, you looked at some examples of how to work with <code>auditd</code>. Next, let’s look at a simpler method of auditing files and directories.</p>



<h2 data-number="13.8">Auditing files and directories with inotifywait</h2>
<p>There might be times when you’ll just want a quick and easy way to monitor a file or a directory in real time. Instead of having audit messages sent to the <code>audit.log</code> file, you can use <code>inotifywait</code> to have a message pop up in your terminal as soon as someone accesses a designated file or directory. This tool is part of the <code>inotify-tools</code> package on both Ubuntu and AlmaLinux. It’s not installed by default, so go ahead and install it if it isn’t already.</p>
<p>To monitor a single file, just do:</p>
<div><pre><code>donnie@donnie-ca:~$ sudo inotifywait -m /secrets/donnie_file.txt
[sudo] password for donnie: 
Setting up watches.
Watches established.
/secrets/donnie_file.txt OPEN 
/secrets/donnie_file.txt CLOSE_NOWRITE,CLOSE</code></pre>
</div>
<p>The <code>/secrets/</code> directory is set so that only someone with root privileges can access it, so I have to use <code>sudo</code> to make this work. The <code>-m</code> option causes <code>inotifywait</code> to perform continuous monitoring, instead of exiting as soon as something happens. The <strong>OPEN</strong> message came up when I opened the file with <code>less</code>, and the <strong>CLOSE_NOWRITE,CLOSE</strong> message came up when I exited <code>less</code>. Now, let’s close this down and monitor the whole directory. All we have to do is to add the <code>-r</code> option and leave out the file name, like this:</p>
<div><pre><code>donnie@donnie-ca:~$ sudo inotifywait -m -r /secrets/
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/secrets/ OPEN donnie_file.txt
/secrets/ CREATE .donnie_file.txt.swp
/secrets/ OPEN .donnie_file.txt.swp
/secrets/ CREATE .donnie_file.txt.swx
. . .
. . .
/secrets/ CLOSE_NOWRITE,CLOSE donnie_file.txt
/secrets/ OPEN donnie_file.txt
/secrets/ CLOSE_NOWRITE,CLOSE donnie_file.txt
/secrets/ MODIFY .donnie_file.txt.swp
/secrets/ MODIFY .donnie_file.txt.swp</code></pre>
</div>
<p>This time, I opened the <code>donnie_file.txt</code> file in <code>vim</code>, which caused a whole bunch of messages to come up. That’s because when you open a file in <code>vim</code>, it creates some temporary files that will get cleared out when you exit <code>vim</code>. (Note that I haven’t actually edited the file yet, and that more messages will get created when I do.)</p>
<p>As good as <code>inotifywait</code> seems to be, there is one downside. It’s just that to use it, you’ll need to stayed glued to your workstation, keep the terminal window from which you’re running <code>inotifywait</code> open, and watch for messages to pop up. There’s no logging mechanism, and no daemon mode. But, if you need to monitor something in real-time, this could be useful.</p>
<p>That’s all there is to it for <code>inotifywait</code>. Next, we'll look at OpenSCAP, which can actually remediate a less-than-secure system.</p>


<h2 data-number="13.9">Applying OpenSCAP policies with oscap</h2>
<p>The <strong>Security Content Automation Protocol</strong> (<strong>SCAP</strong>) was created by the US <strong>National Institute of Standards and Technology</strong> (<strong>NIST</strong>). It consists of hardening guides, hardening templates, and baseline configuration guides for setting up secure systems. OpenSCAP is a set of FOSS tools that can be used to implement SCAP. It consists of the following:</p>
<ul>
<li>Security profiles that you can apply to a system. There are different profiles for meeting the requirements of several different certifying agencies.</li>
<li>Security guides to help with the initial setup of your system.</li>
<li>The <code>oscap</code> command-line utility to apply security templates.</li>
<li>On systems that have a desktop interface, you have SCAP Workbench, a GUI-type utility.</li>
</ul>
<p>You can install OpenSCAP on either the Red Hat or the Ubuntu distros, but it's much better implemented on the Red Hat distros. For one thing, when you install a Red Hat-type operating system, you can choose to apply a SCAP profile during installation. You can't do that with Ubuntu. All of the Red Hat-type distros come with a fairly complete set of ready-to-use profiles. Ubuntu 22.04 comes with outdated profiles for Fedora 14 and RHEL 6, and none for Ubuntu 22.04, which I think is totally bizarre. Not to worry though, because I’ll show you how to get some good Ubuntu profiles in just a bit.</p>
<p>When doing initial system builds, it's desirable to start with a security checklist that's appropriate for your scenario, because there are certain things the OpenSCAP can’t automate for you. Then, use OpenSCAP to do the rest. I'll tell you more about security checklists at the end of <em>Chapter 16</em>, <em>Security Tips and Tricks for the Busy Bee</em>.</p>
<p>All right, let's learn how to install OpenSCAP and how to use the command-line utility that's common to all of our distros.</p>

<h3 data-number="13.9.1">Installing OpenSCAP</h3>
<p>On your CentOS 7 machine, assuming that you didn't install OpenSCAP during the operating system installation, do this:</p>
<div><pre><code>sudo yum install openscap-scanner scap-security-guide</code></pre>
</div>
<p>Do the following for either AlmaLinux 8 or AlmaLinux 9:</p>
<p>sudo dnf install openscap-scanner scap-security-guide</p>
<p>Do the following on an Ubuntu 22.04 machine:</p>
<div><pre><code>sudo apt install python-openscap</code></pre>
</div>


<h3 data-number="13.9.2">Viewing the profile files</h3>
<p>On the CentOS 7 machine and the AlmaLinux machines, you'll see the profile files in the <code>/usr/share/xml/scap/ssg/content/</code> directory.</p>
<p>As I already mentioned, Ubuntu only gives us some outdated Fedora 14 and RHEL 6 profiles in the <code>/usr/share/openscap/</code> directory, and none at all for any flavor of Ubuntu. (Why that is, I have no clue.) The profile files are in <code>.xml</code> format, and each one contains one or more profiles that you can apply to the system. For example, here are some from the CentOS 7 machine:</p>
<div><pre><code>[donnie@localhost content]$ pwd
/usr/share/xml/scap/ssg/content
[donnie@localhost content]$ ls -l
total 50596
-rw-r--r--. 1 root root  6734643 Oct 19 19:40 ssg-centos6-ds.xml
-rw-r--r--. 1 root root  1596043 Oct 19 19:40 ssg-centos6-xccdf.xml
-rw-r--r--. 1 root root 11839886 Oct 19 19:41 ssg-centos7-ds.xml
-rw-r--r--. 1 root root  2636971 Oct 19 19:40 ssg-centos7-xccdf.xml
-rw-r--r--. 1 root root      642 Oct 19 19:40 ssg-firefox-cpe-dictionary.xml
. . .
-rw-r--r--. 1 root root 11961196 Oct 19 19:41 ssg-rhel7-ds.xml
-rw-r--r--. 1 root root   851069 Oct 19 19:40 ssg-rhel7-ocil.xml
-rw-r--r--. 1 root root  2096046 Oct 19 19:40 ssg-rhel7-oval.xml
-rw-r--r--. 1 root root  2863621 Oct 19 19:40 ssg-rhel7-xccdf.xml
[donnie@localhost content]$</code></pre>
</div>
<p>You’ll see a somewhat similar list on your AlmaLinux 8 machine, except that they’ll be specific to AlmaLinux 8. On AlmaLinux 9, things are a bit different. At the time of this writing, all we have is just one profile file. That’s because the RHEL 9 distros are quite new, so the development of SCAP profiles for them isn’t yet complete. Anyway, here’s AlmaLinux 9 file:</p>
<div><pre><code>[donnie@almalinux9 content]$ pwd
/usr/share/xml/scap/ssg/content
[donnie@almalinux9 content]$ ls -l
total 21524
-rw-r--r--. 1 root root 22040119 Oct 27 08:37 ssg-almalinux9-ds.xml
[donnie@almalinux9 content]$</code></pre>
</div>
<p>The command-line utility for working with OpenSCAP is <code>oscap</code>. On our AlmaLinux 9 machine, let's use this with the <code>info</code> switch to view information about any of the profile files. Let's look at the <code>ssg-almalinux9-ds.xml</code> file:</p>
<div><pre><code>[donnie@almalinux9 content]$ pwd
/usr/share/xml/scap/ssg/content
[donnie@almalinux9 content]$ sudo oscap info ssg-almalinux9-ds.xml 
. . .
. . .
    Profiles:
        Title: ANSSI-BP-028 (enhanced)
        Id: xccdf_org.ssgproject.content_profile_anssi_bp28_enhanced
        Title: ANSSI-BP-028 (high)
        Id: xccdf_org.ssgproject.content_profile_anssi_bp28_high
        Title: ANSSI-BP-028 (intermediary)
        Id: xccdf_org.ssgproject.content_profile_anssi_bp28_intermediary
        Title: ANSSI-BP-028 (minimal)
        Id: xccdf_org.ssgproject.content_profile_anssi_bp28_minimal
        . . .</code></pre>
</div>
<p>Due to formatting constraints, I can’t show you the entire list of profiles. So, do this for yourself and scroll down the list. You’ll see profiles for <strong>STIG</strong> and <strong>PCI-DSS</strong>, just as we had for the auditing rules. There’s also a <strong>HIPAA</strong> profile for medical facilities here in the US, several benchmark profiles from the <strong>Center for Internet Security</strong>, (<strong>CIS</strong>), and several that are specific for certain non-US countries, among others.</p>


<h3 data-number="13.9.3">Getting the missing profiles for Ubuntu</h3>
<p>We’ve seen that there aren’t any SCAP profiles for Ubuntu in the Ubuntu repositories. So, is all hope lost for Ubuntu users? Absolutely not. Fortunately, the <code>scap-security-guide</code> package that you can install on a Fedora Server virtual machine comes with SCAP profiles for a variety of other Linux distros, including the newest versions of Ubuntu. So, your best bet for setting up OpenSCAP on Ubuntu is to create a Fedora Server VM, install the <code>scap-security-guide</code> package in the same manner that you just did for AlmaLinux, and then copy the appropriate profile file from Fedora’s <code>/usr/share/xml/scap/ssg/content/</code> directory to your Ubuntu machine. After that, you’re golden.</p>


<h3 data-number="13.9.4">Scanning the system</h3>
<p>In this section, we'll work with our AlmaLinux 9 VM.</p>
<blockquote>
<p>This procedure works the same for most all Linux distros, except that the names of the profiles will differ.</p>
</blockquote>
<p>Now, let's say that we need to ensure that our systems are compliant with <strong>Payment Card Industry</strong> standards. First, we'll scan the AlmaLinux 9 machine to see what needs remediation. (Note that the following command is very long and wraps around on the printed page.):</p>
<div><pre><code>sudo oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_pci-dss --fetch-remote --results scan-xccdf-results.xml /usr/share/xml/scap/ssg/content/ssg-almalinux9-ds.xml</code></pre>
</div>
<p>As we always like to do, let's break this down:</p>
<ul>
<li><code>xccdf eval</code>: The <strong>Extensible Configuration Checklist Description Format</strong> is one of the languages that we can use to write security profile rules. We're going to use a profile that was written in this language to perform an evaluation of the system.</li>
<li><code>--profile xccdf_org.ssgproject.content_profile_pci-dss</code>: Here, I specified that I want to use the Payment Card Industry-Data Security Standard profile to evaluate the system. (Profile names come from the <code>Id</code> lines in the profile file.)</li>
<li><code>--fetch-remote</code>: Use this option to fetch additional rules. (Note that this option won’t work if you have the system crypto policy set to <code>FUTURE</code> mode.)</li>
<li><code>--results scan-xccdf-results.xml</code>: I'm going to save the scan results to this <code>.xml</code> format file. When the scan has finished, I'll create a report from this file.</li>
<li><code>/usr/share/xml/scap/ssg/content/ssg-almalinux9-ds.xml</code>: This is the profile file that contains the <code>xccdf_org.ssgproject.content_profile_pci-dss</code> profile.</li>
</ul>
<p>As the scan progresses, the output will be sent to the screen, as well as to the designated output file. It's a long list of items, so I'll only show you a few of them. Here are a couple of items that look okay:</p>
<div><pre><code>Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
OVAL Definition ID  oval:org.almalinux.alsa:def:20227967
OVAL Definition Title   ALSA-2022:7967: qemu-kvm security, bug fix, and enhancement update (Moderate)
Result  pass
Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
OVAL Definition ID  oval:org.almalinux.alsa:def:20227959
OVAL Definition Title   ALSA-2022:7959: guestfs-tools security, bug fix, and enhancement update (Low)
Result  pass</code></pre>
</div>
<p>Here are a couple of items that need to be fixed:</p>
<div><pre><code>Title   Ensure PAM Displays Last Logon/Access Notification
Rule    xccdf_org.ssgproject.content_rule_display_login_attempts
Result  fail
Title   Limit Password Reuse
Rule    xccdf_org.ssgproject.content_rule_accounts_password_pam_unix_remember
Result  fail
Title   Lock Accounts After Failed Password Attempts
Rule    xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_deny
Result  fail
Title   Set Lockout Time for Failed Password Attempts
Rule    xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_unlock_time
Result  fail</code></pre>
</div>
<p>So, we have patches for certain security vulnerabilities installed, which is good. However, it seems that we have some problems with our password policies.</p>
<p>Now that I've run the scan and created an output file with the results, I can build my report:</p>
<div><pre><code>sudo oscap xccdf generate report scan-xccdf-results.xml &gt; scan-xccdf-results.html</code></pre>
</div>
<p>This extracts information from the <code>.xml</code> format file that isn't meant to be read by humans and transfers it to a <code>.html</code> file that you can open in your web browser. (For the record, the report says that there are 49 problems that need to be fixed.)</p>


<h3 data-number="13.9.5">Remediating the system</h3>
<p>So, we have 49 problems that we need to fix before our system can be considered compliant with Payment Card Industry standards. Let's see how many of them <code>oscap</code> can fix for us:</p>
<div><pre><code>sudo oscap xccdf eval --remediate --profile xccdf_org.ssgproject.content_profile_pci-dss --fetch-remote --results scan-xccdf-results.xml /usr/share/xml/scap/ssg/content/ssg-almalinux9-ds.xml</code></pre>
</div>
<p>This is the same command that I used to perform the initial scan, except that I added the <code>--remediate</code> option and I'm saving the results to a different file. You'll want to have a bit of patience when you run this command because fixing some problems involves downloading and installing software packages. In fact, even as I type this, <code>oscap</code> is busy downloading and installing the missing AIDE intrusion detection system package.</p>
<p>Okay, here are some of the things that were fixed:</p>
<div><pre><code>Title   Verify and Correct File Permissions with RPM
Rule    xccdf_org.ssgproject.content_rule_rpm_verify_permissions
Result  fixed
Title   Install AIDE
Rule    xccdf_org.ssgproject.content_rule_package_aide_installed
Result  fixed
Title   Build and Test AIDE Database
Rule    xccdf_org.ssgproject.content_rule_aide_build_database
Result  fixed
Title   Configure Periodic Execution of AIDE
Rule    xccdf_org.ssgproject.content_rule_aide_periodic_cron_checking</code></pre>
</div>
<p>Result fixed</p>
<div><pre><code>   </code></pre>
</div>
<p>There are a couple of errors because of things that <code>oscap</code> couldn't fix, but that's normal. At least you know about them so that you can try to fix them yourself.</p>
<p>Now, check this out. Do you remember how in <em>Chapter 3, Securing User Accounts</em>, I made you jump through hoops to ensure that users had strong passwords that expire on a regular basis? Well, by applying this OpenSCAP profile, you get all that fixed for you automatically. Here are a few of the items that were fixed:</p>
<div><pre><code>Title   Lock Accounts After Failed Password Attempts
Rule    xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_deny
Result  fixed
Title   Set Lockout Time for Failed Password Attempts
Rule    xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_unlock_time
Result  fixed
Title   Ensure PAM Enforces Password Requirements - Minimum Digit Characters
Rule    xccdf_org.ssgproject.content_rule_accounts_password_pam_dcredit
Result  fixed
Title   Ensure PAM Enforces Password Requirements - Minimum Lowercase Characters
Rule    xccdf_org.ssgproject.content_rule_accounts_password_pam_lcredit
Result  fixed</code></pre>
</div>
<p>So, yeah, OpenSCAP is pretty cool, and even the command-line tools aren't hard to use. However, if you have to use a GUI, we have a tool for that, which we'll look at next.</p>


<h3 data-number="13.9.6">Using SCAP Workbench</h3>
<p>For machines with a desktop environment installed, we have SCAP Workbench. However, if you've ever worked with early versions of the tool, you were likely quite disappointed. Indeed, the early versions of Workbench were so bad that they weren't even usable. Thankfully, things have since improved. Now, Workbench is quite a nice little tool.</p>
<p>To get SCAP Workbench, just use the appropriate installation command. On CentOS 7, do this:</p>
<div><pre><code>sudo yum install scap-workbench</code></pre>
</div>
<p>On AlmaLinux 8 or AlmaLinux 9, do this:</p>
<div><pre><code>sudo dnf install scap-workbench</code></pre>
</div>
<p>On Ubuntu, do the following:</p>
<div><pre><code>sudo apt install scap-workbench</code></pre>
</div>
<p>Yeah, the package name is just <code>scap-workbench</code> instead of <code>openscap-workbench</code>. I don't know why, but I do know that you'll never find it if you're searching for <code>openscap</code> packages.</p>
<p>Once you've installed it, you'll see its menu item on the <strong>Show Applications</strong> portion of the <strong>Activities</strong> page:</p>
<figure>
<img src="img/file76.png" alt="Figure 12.2: SCAP Workbench on the Gnome 3 desktop" /><figcaption aria-hidden="true">Figure 12.2: SCAP Workbench on the Gnome 3 desktop</figcaption>
</figure>
<p>When you first open the program, you would think that the system would ask you for a root or sudo password. But, it doesn't. We'll see if that affects us in a moment.</p>
<p>The first thing you'll see on the opening screen is a drop-down list for you to select the type of content that you want to load. I'll select <strong>AlmaLinux9</strong> and then click on the <strong>Load Content</strong> button:</p>
<figure>
<img src="img/file77.png" alt="Figure 12.3: Select content to load" /><figcaption aria-hidden="true">Figure 12.3: Select content to load</figcaption>
</figure>
<p>Next, you'll see the top panel, where you can select the desired profile. You can also choose to customize the profile, and whether you want to run the scan on the local machine or on a remote machine. In the bottom pane, you'll see a list of rules for that profile. You can expand each rule item to get a description of that rule:</p>
<figure>
<img src="img/file78.png" alt="Figure 12.4: Viewing the rules, and generating a remediation role" /><figcaption aria-hidden="true">Figure 12.4: Viewing the rules, and generating a remediation role</figcaption>
</figure>
<p>At the bottom of this screen, you see some cool options. Click on the <strong>Generate remediation role</strong> button, and you can choose to create a Puppet manifest, an Ansible playbook, or a Bash shell script that you can distribute and apply to other AlmaLinux 9 machines on your network. You can also choose to <strong>Fetch remote resources</strong> and to <strong>Remediate</strong>.</p>
<p>Now, let's click that <strong>Scan</strong> button to see what happens:</p>
<figure>
<img src="img/file79.png" alt="Figure 12.5: Enter your password" /><figcaption aria-hidden="true">Figure 12.5: Enter your password</figcaption>
</figure>
<p>Cool! As I had hoped, it prompts you for your sudo password. Beyond that, I'll leave you to play with it. It's just another one of those GUI-thingies, so the rest of it should be fairly easy to figure out.</p>
<p>Next, we'll take a look at how to choose an appropriate OpenSCAP profile.</p>


<h3 data-number="13.9.7">Choosing an OpenSCAP profile</h3>
<p>So, now, you're saying, <em>Okay, this is all good, but how do I find out what's in these profiles and which one I need?</em> Well, there are several ways.</p>
<p>The first way, which I've just shown you, is to install SCAP Workbench on a machine with a desktop interface and read through the descriptions of all the rules for each profile.</p>
<p>The second way, which might be a bit easier, is to go to the OpenSCAP website and look through the documentation that they have there.</p>
<blockquote>
<p>You'll find information about the available OpenSCAP profiles at <a href="https://www.open-scap.org/security-policies/choosing-policy/">https://www.open-scap.org/security-policies/choosing-policy/</a>.</p>
</blockquote>
<p>As far as knowing which profile to choose, there are a few things to consider:</p>
<ul>
<li>If you work in the financial sector or in a business that does online financial transactions, then go with the <code>pci-dss</code> profile.</li>
<li>If you work for a government agency, especially if it's the US government, then go with either the <code>stig</code> profile or the <code>nispom</code> profile, as dictated by the particular agency.</li>
<li>If neither of these two considerations applies to your situation, then you'll just want to do some research and planning in order to figure out what really needs to be locked down. Look through the rules in each profile and read through the documentation on the OpenSCAP website to help you decide what you need.</li>
</ul>
<p>With Red Hat and its offspring, you can even apply a policy as you install the operating system. We'll look at that next.</p>


<h3 data-number="13.9.8">Applying an OpenSCAP profile during system installation</h3>
<p>One of the things that I love about the Red Hat folk is that they totally get this whole security thing. Yeah, we can lock down other distros and make them more secure, as we've already seen. But with Red Hat distros, it's a bit easier. For a lot of things, the maintainers of the Red Hat-type distros have set secure default options that aren't securely set by default on other distros. (For example, prior to the release of Ubuntu 22.04, Red Hat distros had been the only ones that come with users' home directories locked down by default.) For other things, the Red Hat-type distros come with tools and installation options that help make life easier for a busy, security-conscious administrator.</p>
<p>When you install a Red Hat-type distro, you'll be given the chance to apply an OpenSCAP profile during the operating system installation. Here, on this AlmaLinux 9 installer screen, you'll see the option to choose a security profile in the bottom right-hand corner of the screen:</p>
<figure>
<img src="img/file80.png" alt="Figure 12.6: Select a SCAP profile during installation" /><figcaption aria-hidden="true">Figure 12.6: Select a SCAP profile during installation</figcaption>
</figure>
<p>All you have to do is click on that and then choose your profile:</p>
<figure>
<img src="img/file81.png" alt="Figure: 12.7: Selecting the PCI-DSS profile" /><figcaption aria-hidden="true">Figure: 12.7: Selecting the PCI-DSS profile</figcaption>
</figure>
<p>Okay, that pretty much wraps it up for our discussion of OpenSCAP. The only thing left to add is that, as great as OpenSCAP is, it won't do everything. For example, some security standards require that you have certain directories, such as <code>/home/</code> or <code>/var/</code>, on their own separate partitions. An OpenSCAP scan will alert you if that's not the case, but it can't change your existing partitioning scheme. So, for things like that, you'll need to get a checklist from the governing body that dictates your security requirements and do a bit of advanced work before you even touch OpenSCAP.</p>



<h2 data-number="13.10">Summary</h2>
<p>We covered a lot of ground in this chapter, and we saw some really cool stuff. We began by looking at a couple of antivirus scanners so that we can prevent infecting any Windows machines that access our Linux servers. In the <em>Scanning for rootkits with Rootkit Hunter</em> section, we saw how to scan for those nasty rootkits. We also saw a couple of quick techniques to examine a potentially malicious file. It's important to know how to audit systems, especially in high-security environments, and we saw how to do that. Finally, we wrapped things up with a discussion of hardening our systems with OpenSCAP.</p>
<p>In the next chapter, we'll look at logging and log file security. I'll see you there.</p>


<h2 data-number="13.11">Questions</h2>
<ol>
<li>Which of the following is true about rootkits?
<ol type="A">
<li>They only infect Windows operating systems.</li>
<li>The purpose of planting a rootkit is to gain root privileges to a system.</li>
<li>An intruder must have already gained root privileges in order to plant a rootkit.</li>
<li>A rootkit isn't very harmful.</li>
</ol></li>
<li>Which of the following methods would you use to keep <code>maldet</code> updated?
<ol type="A">
<li>Manually create a <code>cron</code> job that runs every day.</li>
<li>Do nothing, because <code>maldet</code> automatically updates itself.</li>
<li>Once a day, run the normal update command for your operating system.</li>
<li>Run the <code>maldet update</code> utility from the command line.</li>
</ol></li>
<li>Which of the following is true about the <code>auditd</code> service?
<ol type="A">
<li>On an Ubuntu system, you'll need to stop or restart it with the <code>service</code> command.</li>
<li>On a Red Hat-type system, you'll need to stop or restart it with the <code>service</code> command.</li>
<li>On an Ubuntu system, it comes already installed.</li>
<li>On a Red Hat-type system, you'll need to install it yourself.</li>
</ol></li>
<li>You need to create an auditing rule that will alert you every time a particular person reads or creates a file. Which of the following syscalls would you use in that rule?
<ol type="A">
<li><code>openfile</code></li>
<li><code>fileread</code></li>
<li><code>openat</code></li>
<li><code>fileopen</code></li>
</ol></li>
<li>Which file does the <code>auditd</code> service use to log auditing events?
<ol type="A">
<li><code>/var/log/messages</code></li>
<li><code>/var/log/syslog</code></li>
<li><code>/var/log/auditd/audit</code></li>
<li><code>/var/log/audit/audit.log</code></li>
</ol></li>
<li>You need to create custom auditing rules for <code>auditd</code>. Where would you place the new rules?
<ol type="A">
<li><code>/usr/share/audit-version_number/</code></li>
<li><code>/etc/audit/</code></li>
<li><code>/etc/audit.d/rules/</code></li>
<li><code>/etc/audit/rules.d/</code></li>
</ol></li>
<li>You're setting up a web server for a bank's customer portal. Which of the following SCAP profiles might you apply?
<ol type="A">
<li>STIG</li>
<li>NISPOM</li>
<li>PCI-DSS</li>
<li>Sarbanes-Oxley</li>
</ol></li>
<li>Which of the following is true about OpenSCAP?
<ol type="A">
<li>It can't remediate everything, so you'll need to do advance planning with a checklist before setting up a server.</li>
<li>It can automatically remediate every problem on your system.</li>
<li>It's only available for Red Hat-type distros.</li>
<li>Ubuntu comes with a better selection of SCAP profiles.</li>
</ol></li>
<li>Which of the following commands would you use to generate a user authentication report?
<ol type="A">
<li><code>sudo ausearch -au</code></li>
<li><code>sudo aureport -au</code></li>
<li>Define an audit rule, then do <code>sudo ausearch -au</code>.</li>
<li>Define an audit rule, then do <code>sudo aureport -au</code>.</li>
</ol></li>
<li>Which set of Rootkit Hunter options would you use to have a rootkit scan automatically run every night?
<ol type="A">
<li><code>-c</code></li>
<li><code>-c --rwo</code></li>
<li><code>--rwo</code></li>
<li><code>-c --cronjob --rwo</code></li>
</ol></li>
</ol>


<h2 data-number="13.12">Further reading</h2>
<ul>
<li>How to install and configure maldet: <a href="https://www.servernoobs.com/how-to-install-and-configure-maldet-linux-malware-detect-lmd/">https://www.servernoobs.com/how-to-install-and-configure-maldet-linux-malware-detect-lmd/</a></li>
<li>Symbiote: Evasive Linux rootkit malware: <a href="https://www.theregister.com/2022/06/10/symbiote_linux_malware/">https://www.theregister.com/2022/06/10/symbiote_linux_malware/</a></li>
<li>Configuring and auditing Linux systems with <code>auditd</code> daemon: <a href="https://linux-audit.com/configuring-and-auditing-linux-systems-with-audit-daemon/">https://linux-audit.com/configuring-and-auditing-linux-systems-with-audit-daemon/</a></li>
<li>Monitor changes in directories with <code>inotifywatch</code>: <a href="https://distrowatch.com/weekly.php?issue=20220905">https://distrowatch.com/weekly.php?issue=20220905</a></li>
<li>The OpenSCAP portal: <a href="https://www.open-scap.org/">https://www.open-scap.org/</a></li>
<li>Practical OpenSCAP: <a href="https://www.redhat.com/files/summit/session-assets/2016/SL45190-practical-openscap_security-standard-compliance-and-reporting.pdf">https://www.redhat.com/files/summit/session-assets/2016/SL45190-practical-openscap_security-standard-compliance-and-reporting.pdf</a></li>
<li>Center for Internet Security (CIS) benchmarks: <a href="https://www.cisecurity.org/cis-benchmarks/">https://www.cisecurity.org/cis-benchmarks/</a></li>
<li>Auditing the System documentation for RHEL 9: <a href="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/security_hardening/auditing-the-system_security-hardening#doc-wrapper">https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/security_hardening/auditing-the-system_security-hardening#doc-wrapper</a></li>
</ul>


<h2 data-number="13.13">Answers</h2>
<ol>
<li>c</li>
<li>b</li>
<li>b</li>
<li>c</li>
<li>d</li>
<li>d</li>
<li>c</li>
<li>a</li>
<li>b</li>
<li>d</li>
</ol>


</body>
</html>
